# coding: utf-8

# flake8: noqa

"""
    Sendmux API

    Programmatic access to your Sendmux email infrastructure.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.3.0"

# Define package exports
__all__ = [
    "MailboxAPIApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiError",
    "ApiErrorDetail",
    "ApiErrorError",
    "ApiErrorMeta",
    "BatchDeleteMailboxMessagesBody",
    "BatchUpdateMailboxMessagesBody",
    "CreateMailboxFolderBody",
    "CursorPagination",
    "GrantedMailbox",
    "GrantedMailboxListResponse",
    "Mailbox",
    "MailboxAddress",
    "MailboxAttachment",
    "MailboxAttachmentUploadIntentBody",
    "MailboxAttachmentUploadIntentResult",
    "MailboxAttachmentUploadIntentResultHeaders",
    "MailboxAttachmentUploadIntentResultResponse",
    "MailboxAttachmentUploadResult",
    "MailboxAttachmentUploadResultResponse",
    "MailboxBatchDeleteMessagesResult",
    "MailboxBatchDeleteMessagesResultResponse",
    "MailboxBatchGetBody",
    "MailboxBatchGetItem",
    "MailboxBatchGetResult",
    "MailboxBatchGetResultResponse",
    "MailboxBatchGetResultStates",
    "MailboxBatchMessageFailure",
    "MailboxBatchMessageStates",
    "MailboxBatchUpdateMessagesResult",
    "MailboxBatchUpdateMessagesResultResponse",
    "MailboxChanges",
    "MailboxChangesResponse",
    "MailboxContentHeaders",
    "MailboxContentHeadersFullInner",
    "MailboxContentHeadersSelected",
    "MailboxFolder",
    "MailboxFolderCursorListResponse",
    "MailboxFolderDeletedResponse",
    "MailboxFolderDeletedResponseAllOfData",
    "MailboxFolderQueryChanges",
    "MailboxFolderQueryChangesAddedInner",
    "MailboxFolderQueryChangesResponse",
    "MailboxFolderResponse",
    "MailboxGetChanges200Response",
    "MailboxIdentity",
    "MailboxIdentityCursorListResponse",
    "MailboxIdentityResponse",
    "MailboxMe",
    "MailboxMeItemResponse",
    "MailboxMessage",
    "MailboxMessageContent",
    "MailboxMessageContentBody",
    "MailboxMessageContentDates",
    "MailboxMessageContentParticipants",
    "MailboxMessageContentResponse",
    "MailboxMessageContentResponseAllOfData",
    "MailboxMessageContentStates",
    "MailboxMessageCount",
    "MailboxMessageCountResponse",
    "MailboxMessageDeletedResponse",
    "MailboxMessageDetailResponse",
    "MailboxMessageFlags",
    "MailboxMessageQueryChanges",
    "MailboxMessageQueryChangesResponse",
    "MailboxMessageSummary",
    "MailboxMessageSummaryCursorListResponse",
    "MailboxQuota",
    "MailboxQuotaCursorListResponse",
    "MailboxRawBody",
    "MailboxRawBodyBody",
    "MailboxRawBodyResponse",
    "MailboxRawBodyResponseAllOfData",
    "MailboxRealtimeEvent",
    "MailboxRealtimeMessage",
    "MailboxRealtimeMessageAllOfBody",
    "MailboxSearchSnippet",
    "MailboxSearchSnippetsResult",
    "MailboxSearchSnippetsResultResponse",
    "MailboxSendResultResponse",
    "MailboxSendScope",
    "MailboxSession",
    "MailboxSessionCapabilities",
    "MailboxSessionCapabilitiesAttachments",
    "MailboxSessionCapabilitiesFolders",
    "MailboxSessionCapabilitiesIdentities",
    "MailboxSessionCapabilitiesMessages",
    "MailboxSessionCapabilitiesQuotas",
    "MailboxSessionCapabilitiesSubmissions",
    "MailboxSessionCapabilitiesSync",
    "MailboxSessionCapabilitiesThreads",
    "MailboxSessionEndpoints",
    "MailboxSessionGated",
    "MailboxSessionLimits",
    "MailboxSessionMailbox",
    "MailboxSessionResponse",
    "MailboxSessionStates",
    "MailboxSubmission",
    "MailboxSubmissionCursorListResponse",
    "MailboxSubmissionDeliveryStatus",
    "MailboxSubmissionEnvelope",
    "MailboxSubmissionEnvelopeAddress",
    "MailboxSubmissionEnvelopeRcptToInner",
    "MailboxSubmissionResponse",
    "MailboxThread",
    "MailboxThreadContentMeta",
    "MailboxThreadContentMetaStates",
    "MailboxThreadContentResponse",
    "MailboxThreadContentResponseAllOfData",
    "MailboxThreadDetailResponse",
    "MailboxThreadSummary",
    "MailboxThreadSummaryCursorListResponse",
    "MailboxThreadSummaryStates",
    "MailboxTypedChanges",
    "MailboxTypedChangesResponse",
    "MailboxTypedChangesTypes",
    "MailboxUsage",
    "MailboxUsageResource",
    "MailboxUsageResponse",
    "MailboxUsageStates",
    "PatchMailboxFolderBody",
    "PatchMailboxMessageBody",
    "ResponseMeta",
    "SendMailboxMessageBody",
    "SendMailboxMessageBodyAttachmentsInner",
    "SendMailboxMessageBodyAttachmentsInnerAnyOf",
    "SendMailboxMessageBodyAttachmentsInnerAnyOf1",
    "SendMailboxMessageResult",
    "SuccessEnvelope",
    "UpdateMailboxIdentityBody",
]

# import apis into sdk package
from sendmux_mailbox.api.mailbox_api_api import MailboxAPIApi as MailboxAPIApi

# import ApiClient
from sendmux_mailbox.api_response import ApiResponse as ApiResponse
from sendmux_mailbox.api_client import ApiClient as ApiClient
from sendmux_mailbox.configuration import Configuration as Configuration
from sendmux_mailbox.exceptions import OpenApiException as OpenApiException
from sendmux_mailbox.exceptions import ApiTypeError as ApiTypeError
from sendmux_mailbox.exceptions import ApiValueError as ApiValueError
from sendmux_mailbox.exceptions import ApiKeyError as ApiKeyError
from sendmux_mailbox.exceptions import ApiAttributeError as ApiAttributeError
from sendmux_mailbox.exceptions import ApiException as ApiException

# import models into sdk package
from sendmux_mailbox.models.api_error import ApiError as ApiError
from sendmux_mailbox.models.api_error_detail import ApiErrorDetail as ApiErrorDetail
from sendmux_mailbox.models.api_error_error import ApiErrorError as ApiErrorError
from sendmux_mailbox.models.api_error_meta import ApiErrorMeta as ApiErrorMeta
from sendmux_mailbox.models.batch_delete_mailbox_messages_body import BatchDeleteMailboxMessagesBody as BatchDeleteMailboxMessagesBody
from sendmux_mailbox.models.batch_update_mailbox_messages_body import BatchUpdateMailboxMessagesBody as BatchUpdateMailboxMessagesBody
from sendmux_mailbox.models.create_mailbox_folder_body import CreateMailboxFolderBody as CreateMailboxFolderBody
from sendmux_mailbox.models.cursor_pagination import CursorPagination as CursorPagination
from sendmux_mailbox.models.granted_mailbox import GrantedMailbox as GrantedMailbox
from sendmux_mailbox.models.granted_mailbox_list_response import GrantedMailboxListResponse as GrantedMailboxListResponse
from sendmux_mailbox.models.mailbox import Mailbox as Mailbox
from sendmux_mailbox.models.mailbox_address import MailboxAddress as MailboxAddress
from sendmux_mailbox.models.mailbox_attachment import MailboxAttachment as MailboxAttachment
from sendmux_mailbox.models.mailbox_attachment_upload_intent_body import MailboxAttachmentUploadIntentBody as MailboxAttachmentUploadIntentBody
from sendmux_mailbox.models.mailbox_attachment_upload_intent_result import MailboxAttachmentUploadIntentResult as MailboxAttachmentUploadIntentResult
from sendmux_mailbox.models.mailbox_attachment_upload_intent_result_headers import MailboxAttachmentUploadIntentResultHeaders as MailboxAttachmentUploadIntentResultHeaders
from sendmux_mailbox.models.mailbox_attachment_upload_intent_result_response import MailboxAttachmentUploadIntentResultResponse as MailboxAttachmentUploadIntentResultResponse
from sendmux_mailbox.models.mailbox_attachment_upload_result import MailboxAttachmentUploadResult as MailboxAttachmentUploadResult
from sendmux_mailbox.models.mailbox_attachment_upload_result_response import MailboxAttachmentUploadResultResponse as MailboxAttachmentUploadResultResponse
from sendmux_mailbox.models.mailbox_batch_delete_messages_result import MailboxBatchDeleteMessagesResult as MailboxBatchDeleteMessagesResult
from sendmux_mailbox.models.mailbox_batch_delete_messages_result_response import MailboxBatchDeleteMessagesResultResponse as MailboxBatchDeleteMessagesResultResponse
from sendmux_mailbox.models.mailbox_batch_get_body import MailboxBatchGetBody as MailboxBatchGetBody
from sendmux_mailbox.models.mailbox_batch_get_item import MailboxBatchGetItem as MailboxBatchGetItem
from sendmux_mailbox.models.mailbox_batch_get_result import MailboxBatchGetResult as MailboxBatchGetResult
from sendmux_mailbox.models.mailbox_batch_get_result_response import MailboxBatchGetResultResponse as MailboxBatchGetResultResponse
from sendmux_mailbox.models.mailbox_batch_get_result_states import MailboxBatchGetResultStates as MailboxBatchGetResultStates
from sendmux_mailbox.models.mailbox_batch_message_failure import MailboxBatchMessageFailure as MailboxBatchMessageFailure
from sendmux_mailbox.models.mailbox_batch_message_states import MailboxBatchMessageStates as MailboxBatchMessageStates
from sendmux_mailbox.models.mailbox_batch_update_messages_result import MailboxBatchUpdateMessagesResult as MailboxBatchUpdateMessagesResult
from sendmux_mailbox.models.mailbox_batch_update_messages_result_response import MailboxBatchUpdateMessagesResultResponse as MailboxBatchUpdateMessagesResultResponse
from sendmux_mailbox.models.mailbox_changes import MailboxChanges as MailboxChanges
from sendmux_mailbox.models.mailbox_changes_response import MailboxChangesResponse as MailboxChangesResponse
from sendmux_mailbox.models.mailbox_content_headers import MailboxContentHeaders as MailboxContentHeaders
from sendmux_mailbox.models.mailbox_content_headers_full_inner import MailboxContentHeadersFullInner as MailboxContentHeadersFullInner
from sendmux_mailbox.models.mailbox_content_headers_selected import MailboxContentHeadersSelected as MailboxContentHeadersSelected
from sendmux_mailbox.models.mailbox_folder import MailboxFolder as MailboxFolder
from sendmux_mailbox.models.mailbox_folder_cursor_list_response import MailboxFolderCursorListResponse as MailboxFolderCursorListResponse
from sendmux_mailbox.models.mailbox_folder_deleted_response import MailboxFolderDeletedResponse as MailboxFolderDeletedResponse
from sendmux_mailbox.models.mailbox_folder_deleted_response_all_of_data import MailboxFolderDeletedResponseAllOfData as MailboxFolderDeletedResponseAllOfData
from sendmux_mailbox.models.mailbox_folder_query_changes import MailboxFolderQueryChanges as MailboxFolderQueryChanges
from sendmux_mailbox.models.mailbox_folder_query_changes_added_inner import MailboxFolderQueryChangesAddedInner as MailboxFolderQueryChangesAddedInner
from sendmux_mailbox.models.mailbox_folder_query_changes_response import MailboxFolderQueryChangesResponse as MailboxFolderQueryChangesResponse
from sendmux_mailbox.models.mailbox_folder_response import MailboxFolderResponse as MailboxFolderResponse
from sendmux_mailbox.models.mailbox_get_changes200_response import MailboxGetChanges200Response as MailboxGetChanges200Response
from sendmux_mailbox.models.mailbox_identity import MailboxIdentity as MailboxIdentity
from sendmux_mailbox.models.mailbox_identity_cursor_list_response import MailboxIdentityCursorListResponse as MailboxIdentityCursorListResponse
from sendmux_mailbox.models.mailbox_identity_response import MailboxIdentityResponse as MailboxIdentityResponse
from sendmux_mailbox.models.mailbox_me import MailboxMe as MailboxMe
from sendmux_mailbox.models.mailbox_me_item_response import MailboxMeItemResponse as MailboxMeItemResponse
from sendmux_mailbox.models.mailbox_message import MailboxMessage as MailboxMessage
from sendmux_mailbox.models.mailbox_message_content import MailboxMessageContent as MailboxMessageContent
from sendmux_mailbox.models.mailbox_message_content_body import MailboxMessageContentBody as MailboxMessageContentBody
from sendmux_mailbox.models.mailbox_message_content_dates import MailboxMessageContentDates as MailboxMessageContentDates
from sendmux_mailbox.models.mailbox_message_content_participants import MailboxMessageContentParticipants as MailboxMessageContentParticipants
from sendmux_mailbox.models.mailbox_message_content_response import MailboxMessageContentResponse as MailboxMessageContentResponse
from sendmux_mailbox.models.mailbox_message_content_response_all_of_data import MailboxMessageContentResponseAllOfData as MailboxMessageContentResponseAllOfData
from sendmux_mailbox.models.mailbox_message_content_states import MailboxMessageContentStates as MailboxMessageContentStates
from sendmux_mailbox.models.mailbox_message_count import MailboxMessageCount as MailboxMessageCount
from sendmux_mailbox.models.mailbox_message_count_response import MailboxMessageCountResponse as MailboxMessageCountResponse
from sendmux_mailbox.models.mailbox_message_deleted_response import MailboxMessageDeletedResponse as MailboxMessageDeletedResponse
from sendmux_mailbox.models.mailbox_message_detail_response import MailboxMessageDetailResponse as MailboxMessageDetailResponse
from sendmux_mailbox.models.mailbox_message_flags import MailboxMessageFlags as MailboxMessageFlags
from sendmux_mailbox.models.mailbox_message_query_changes import MailboxMessageQueryChanges as MailboxMessageQueryChanges
from sendmux_mailbox.models.mailbox_message_query_changes_response import MailboxMessageQueryChangesResponse as MailboxMessageQueryChangesResponse
from sendmux_mailbox.models.mailbox_message_summary import MailboxMessageSummary as MailboxMessageSummary
from sendmux_mailbox.models.mailbox_message_summary_cursor_list_response import MailboxMessageSummaryCursorListResponse as MailboxMessageSummaryCursorListResponse
from sendmux_mailbox.models.mailbox_quota import MailboxQuota as MailboxQuota
from sendmux_mailbox.models.mailbox_quota_cursor_list_response import MailboxQuotaCursorListResponse as MailboxQuotaCursorListResponse
from sendmux_mailbox.models.mailbox_raw_body import MailboxRawBody as MailboxRawBody
from sendmux_mailbox.models.mailbox_raw_body_body import MailboxRawBodyBody as MailboxRawBodyBody
from sendmux_mailbox.models.mailbox_raw_body_response import MailboxRawBodyResponse as MailboxRawBodyResponse
from sendmux_mailbox.models.mailbox_raw_body_response_all_of_data import MailboxRawBodyResponseAllOfData as MailboxRawBodyResponseAllOfData
from sendmux_mailbox.models.mailbox_realtime_event import MailboxRealtimeEvent as MailboxRealtimeEvent
from sendmux_mailbox.models.mailbox_realtime_message import MailboxRealtimeMessage as MailboxRealtimeMessage
from sendmux_mailbox.models.mailbox_realtime_message_all_of_body import MailboxRealtimeMessageAllOfBody as MailboxRealtimeMessageAllOfBody
from sendmux_mailbox.models.mailbox_search_snippet import MailboxSearchSnippet as MailboxSearchSnippet
from sendmux_mailbox.models.mailbox_search_snippets_result import MailboxSearchSnippetsResult as MailboxSearchSnippetsResult
from sendmux_mailbox.models.mailbox_search_snippets_result_response import MailboxSearchSnippetsResultResponse as MailboxSearchSnippetsResultResponse
from sendmux_mailbox.models.mailbox_send_result_response import MailboxSendResultResponse as MailboxSendResultResponse
from sendmux_mailbox.models.mailbox_send_scope import MailboxSendScope as MailboxSendScope
from sendmux_mailbox.models.mailbox_session import MailboxSession as MailboxSession
from sendmux_mailbox.models.mailbox_session_capabilities import MailboxSessionCapabilities as MailboxSessionCapabilities
from sendmux_mailbox.models.mailbox_session_capabilities_attachments import MailboxSessionCapabilitiesAttachments as MailboxSessionCapabilitiesAttachments
from sendmux_mailbox.models.mailbox_session_capabilities_folders import MailboxSessionCapabilitiesFolders as MailboxSessionCapabilitiesFolders
from sendmux_mailbox.models.mailbox_session_capabilities_identities import MailboxSessionCapabilitiesIdentities as MailboxSessionCapabilitiesIdentities
from sendmux_mailbox.models.mailbox_session_capabilities_messages import MailboxSessionCapabilitiesMessages as MailboxSessionCapabilitiesMessages
from sendmux_mailbox.models.mailbox_session_capabilities_quotas import MailboxSessionCapabilitiesQuotas as MailboxSessionCapabilitiesQuotas
from sendmux_mailbox.models.mailbox_session_capabilities_submissions import MailboxSessionCapabilitiesSubmissions as MailboxSessionCapabilitiesSubmissions
from sendmux_mailbox.models.mailbox_session_capabilities_sync import MailboxSessionCapabilitiesSync as MailboxSessionCapabilitiesSync
from sendmux_mailbox.models.mailbox_session_capabilities_threads import MailboxSessionCapabilitiesThreads as MailboxSessionCapabilitiesThreads
from sendmux_mailbox.models.mailbox_session_endpoints import MailboxSessionEndpoints as MailboxSessionEndpoints
from sendmux_mailbox.models.mailbox_session_gated import MailboxSessionGated as MailboxSessionGated
from sendmux_mailbox.models.mailbox_session_limits import MailboxSessionLimits as MailboxSessionLimits
from sendmux_mailbox.models.mailbox_session_mailbox import MailboxSessionMailbox as MailboxSessionMailbox
from sendmux_mailbox.models.mailbox_session_response import MailboxSessionResponse as MailboxSessionResponse
from sendmux_mailbox.models.mailbox_session_states import MailboxSessionStates as MailboxSessionStates
from sendmux_mailbox.models.mailbox_submission import MailboxSubmission as MailboxSubmission
from sendmux_mailbox.models.mailbox_submission_cursor_list_response import MailboxSubmissionCursorListResponse as MailboxSubmissionCursorListResponse
from sendmux_mailbox.models.mailbox_submission_delivery_status import MailboxSubmissionDeliveryStatus as MailboxSubmissionDeliveryStatus
from sendmux_mailbox.models.mailbox_submission_envelope import MailboxSubmissionEnvelope as MailboxSubmissionEnvelope
from sendmux_mailbox.models.mailbox_submission_envelope_address import MailboxSubmissionEnvelopeAddress as MailboxSubmissionEnvelopeAddress
from sendmux_mailbox.models.mailbox_submission_envelope_rcpt_to_inner import MailboxSubmissionEnvelopeRcptToInner as MailboxSubmissionEnvelopeRcptToInner
from sendmux_mailbox.models.mailbox_submission_response import MailboxSubmissionResponse as MailboxSubmissionResponse
from sendmux_mailbox.models.mailbox_thread import MailboxThread as MailboxThread
from sendmux_mailbox.models.mailbox_thread_content_meta import MailboxThreadContentMeta as MailboxThreadContentMeta
from sendmux_mailbox.models.mailbox_thread_content_meta_states import MailboxThreadContentMetaStates as MailboxThreadContentMetaStates
from sendmux_mailbox.models.mailbox_thread_content_response import MailboxThreadContentResponse as MailboxThreadContentResponse
from sendmux_mailbox.models.mailbox_thread_content_response_all_of_data import MailboxThreadContentResponseAllOfData as MailboxThreadContentResponseAllOfData
from sendmux_mailbox.models.mailbox_thread_detail_response import MailboxThreadDetailResponse as MailboxThreadDetailResponse
from sendmux_mailbox.models.mailbox_thread_summary import MailboxThreadSummary as MailboxThreadSummary
from sendmux_mailbox.models.mailbox_thread_summary_cursor_list_response import MailboxThreadSummaryCursorListResponse as MailboxThreadSummaryCursorListResponse
from sendmux_mailbox.models.mailbox_thread_summary_states import MailboxThreadSummaryStates as MailboxThreadSummaryStates
from sendmux_mailbox.models.mailbox_typed_changes import MailboxTypedChanges as MailboxTypedChanges
from sendmux_mailbox.models.mailbox_typed_changes_response import MailboxTypedChangesResponse as MailboxTypedChangesResponse
from sendmux_mailbox.models.mailbox_typed_changes_types import MailboxTypedChangesTypes as MailboxTypedChangesTypes
from sendmux_mailbox.models.mailbox_usage import MailboxUsage as MailboxUsage
from sendmux_mailbox.models.mailbox_usage_resource import MailboxUsageResource as MailboxUsageResource
from sendmux_mailbox.models.mailbox_usage_response import MailboxUsageResponse as MailboxUsageResponse
from sendmux_mailbox.models.mailbox_usage_states import MailboxUsageStates as MailboxUsageStates
from sendmux_mailbox.models.patch_mailbox_folder_body import PatchMailboxFolderBody as PatchMailboxFolderBody
from sendmux_mailbox.models.patch_mailbox_message_body import PatchMailboxMessageBody as PatchMailboxMessageBody
from sendmux_mailbox.models.response_meta import ResponseMeta as ResponseMeta
from sendmux_mailbox.models.send_mailbox_message_body import SendMailboxMessageBody as SendMailboxMessageBody
from sendmux_mailbox.models.send_mailbox_message_body_attachments_inner import SendMailboxMessageBodyAttachmentsInner as SendMailboxMessageBodyAttachmentsInner
from sendmux_mailbox.models.send_mailbox_message_body_attachments_inner_any_of import SendMailboxMessageBodyAttachmentsInnerAnyOf as SendMailboxMessageBodyAttachmentsInnerAnyOf
from sendmux_mailbox.models.send_mailbox_message_body_attachments_inner_any_of1 import SendMailboxMessageBodyAttachmentsInnerAnyOf1 as SendMailboxMessageBodyAttachmentsInnerAnyOf1
from sendmux_mailbox.models.send_mailbox_message_result import SendMailboxMessageResult as SendMailboxMessageResult
from sendmux_mailbox.models.success_envelope import SuccessEnvelope as SuccessEnvelope
from sendmux_mailbox.models.update_mailbox_identity_body import UpdateMailboxIdentityBody as UpdateMailboxIdentityBody


from sendmux_mailbox.client import (
    DEFAULT_BASE_URL,
    SendmuxMailboxApiClient,
    configure_mailbox,
    create_mailbox_client,
)

from sendmux_mailbox.events import iter_mailbox_events
from sendmux_mailbox.attachments import (
    create_mailbox_attachment_upload_from_file,
    download_mailbox_attachment,
    read_mailbox_text_attachment,
    send_mailbox_message_with_files,
    upload_mailbox_attachment_from_file,
    upload_mailbox_attachment_via_presigned_file,
)
