# coding: utf-8

"""
    Sendmux API

    Programmatic access to your Sendmux email infrastructure.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sendmux_mailbox.models.mailbox_batch_get_result_states import MailboxBatchGetResultStates
from sendmux_mailbox.models.mailbox_raw_body_body import MailboxRawBodyBody
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailboxRawBodyResponseAllOfData(BaseModel):
    """
    MailboxRawBodyResponseAllOfData
    """ # noqa: E501
    body: MailboxRawBodyBody
    id: StrictStr = Field(description="Message ID")
    part: StrictStr
    states: MailboxBatchGetResultStates
    thread_id: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["body", "id", "part", "states", "thread_id"]

    @field_validator('part')
    def part_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['text', 'html', 'both']):
            raise ValueError("must be one of enum values ('text', 'html', 'both')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailboxRawBodyResponseAllOfData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of body
        if self.body:
            _dict['body'] = self.body.to_dict()
        # override the default output from pydantic by calling `to_dict()` of states
        if self.states:
            _dict['states'] = self.states.to_dict()
        # set to None if thread_id (nullable) is None
        # and model_fields_set contains the field
        if self.thread_id is None and "thread_id" in self.model_fields_set:
            _dict['thread_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailboxRawBodyResponseAllOfData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "body": MailboxRawBodyBody.from_dict(obj["body"]) if obj.get("body") is not None else None,
            "id": obj.get("id"),
            "part": obj.get("part"),
            "states": MailboxBatchGetResultStates.from_dict(obj["states"]) if obj.get("states") is not None else None,
            "thread_id": obj.get("thread_id")
        })
        return _obj


