# coding: utf-8

"""
    Sendmux API

    Programmatic access to your Sendmux email infrastructure.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sendmux_mailbox.models.mailbox_realtime_message import MailboxRealtimeMessage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailboxRealtimeEvent(BaseModel):
    """
    MailboxRealtimeEvent
    """ # noqa: E501
    event_type: StrictStr
    is_spam: Optional[StrictBool]
    mailbox_id: StrictStr
    message: MailboxRealtimeMessage
    message_id: Optional[StrictStr]
    message_id_kind: Optional[StrictStr]
    occurred_at: StrictStr
    recipients: List[StrictStr]
    sender: Optional[StrictStr]
    team_public_id: StrictStr
    __properties: ClassVar[List[str]] = ["event_type", "is_spam", "mailbox_id", "message", "message_id", "message_id_kind", "occurred_at", "recipients", "sender", "team_public_id"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['message.received', 'message.received.spam', 'sync_required']):
            raise ValueError("must be one of enum values ('message.received', 'message.received.spam', 'sync_required')")
        return value

    @field_validator('message_id_kind')
    def message_id_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['provider', 'rfc5322']):
            raise ValueError("must be one of enum values ('provider', 'rfc5322')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailboxRealtimeEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of message
        if self.message:
            _dict['message'] = self.message.to_dict()
        # set to None if is_spam (nullable) is None
        # and model_fields_set contains the field
        if self.is_spam is None and "is_spam" in self.model_fields_set:
            _dict['is_spam'] = None

        # set to None if message_id (nullable) is None
        # and model_fields_set contains the field
        if self.message_id is None and "message_id" in self.model_fields_set:
            _dict['message_id'] = None

        # set to None if message_id_kind (nullable) is None
        # and model_fields_set contains the field
        if self.message_id_kind is None and "message_id_kind" in self.model_fields_set:
            _dict['message_id_kind'] = None

        # set to None if sender (nullable) is None
        # and model_fields_set contains the field
        if self.sender is None and "sender" in self.model_fields_set:
            _dict['sender'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailboxRealtimeEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_type": obj.get("event_type"),
            "is_spam": obj.get("is_spam"),
            "mailbox_id": obj.get("mailbox_id"),
            "message": MailboxRealtimeMessage.from_dict(obj["message"]) if obj.get("message") is not None else None,
            "message_id": obj.get("message_id"),
            "message_id_kind": obj.get("message_id_kind"),
            "occurred_at": obj.get("occurred_at"),
            "recipients": obj.get("recipients"),
            "sender": obj.get("sender"),
            "team_public_id": obj.get("team_public_id")
        })
        return _obj


