// Code generated by scripts/generate-go.mjs. DO NOT EDIT.
package management

// Deprecated type names kept as aliases of their replacements until the next major release. The
// table lives in scripts/generate-go.mjs; an alias appears once its former type has left the
// generated output.
