// Code generated by ogen, DO NOT EDIT.

package management

// setDefaults set default value of fields.
func (s *MailboxSendPolicyAllowedFrom) setDefaults() {
	{
		val := bool(true)
		s.OwnAddress.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MailboxSendPolicyAllowedReplyTo) setDefaults() {
	{
		val := bool(true)
		s.OwnAddress.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReplaceMailboxSendPolicyPolicyAllowedFrom) setDefaults() {
	{
		val := bool(true)
		s.OwnAddress.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReplaceMailboxSendPolicyPolicyAllowedReplyTo) setDefaults() {
	{
		val := bool(true)
		s.OwnAddress.SetTo(val)
	}
}
