// Code generated by ogen, DO NOT EDIT.

package management

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	// Sendmux API key. Use a root API key for Management API routes, or a mailbox credential for Mailbox
	// API routes. Obtain keys from the dashboard under API Keys.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBearerAuth = map[string][]string{
	ManagementActivateProviderOperation:                   []string{},
	ManagementCreateDomainOperation:                       []string{},
	ManagementCreateMailboxOperation:                      []string{},
	ManagementCreateMailboxKeyOperation:                   []string{},
	ManagementCreateProviderOperation:                     []string{},
	ManagementCreateSharedAmazonSesLimitRequestOperation:  []string{},
	ManagementCreateWebhookOperation:                      []string{},
	ManagementDeactivateProviderOperation:                 []string{},
	ManagementDeleteDomainOperation:                       []string{},
	ManagementDeleteMailboxOperation:                      []string{},
	ManagementDeleteMailboxKeyOperation:                   []string{},
	ManagementDeleteProviderOperation:                     []string{},
	ManagementDeleteWebhookOperation:                      []string{},
	ManagementGetDeliveryPayloadOperation:                 []string{},
	ManagementGetDomainOperation:                          []string{},
	ManagementGetDomainFiltersOperation:                   []string{},
	ManagementGetDomainZoneFileOperation:                  []string{},
	ManagementGetEmailLogOperation:                        []string{},
	ManagementGetEmailMetricsOperation:                    []string{},
	ManagementGetInboxLogOperation:                        []string{},
	ManagementGetMailboxOperation:                         []string{},
	ManagementGetMailboxFiltersOperation:                  []string{},
	ManagementGetProviderOperation:                        []string{},
	ManagementGetProviderLimitsOperation:                  []string{},
	ManagementGetProviderStatsOperation:                   []string{},
	ManagementGetProviderUsageOperation:                   []string{},
	ManagementGetSharedAmazonSesLimitRequestOperation:     []string{},
	ManagementGetSpendSummaryOperation:                    []string{},
	ManagementGetWebhookOperation:                         []string{},
	ManagementListBalanceOperation:                        []string{},
	ManagementListDeliveryOperation:                       []string{},
	ManagementListDomainsOperation:                        []string{},
	ManagementListEmailLogsOperation:                      []string{},
	ManagementListInboxLogsOperation:                      []string{},
	ManagementListMailboxesOperation:                      []string{},
	ManagementListProvidersOperation:                      []string{},
	ManagementListTransactionsOperation:                   []string{},
	ManagementListWebhooksOperation:                       []string{},
	ManagementRequestSendingAccountLimitIncreaseOperation: []string{},
	ManagementResumeMailboxOperation:                      []string{},
	ManagementRotateWebhookSecretOperation:                []string{},
	ManagementSetDomainFiltersOperation:                   []string{},
	ManagementSetMailboxFiltersOperation:                  []string{},
	ManagementSuspendMailboxOperation:                     []string{},
	ManagementTestProviderOperation:                       []string{},
	ManagementTestWebhookOperation:                        []string{},
	ManagementUpdateMailboxOperation:                      []string{},
	ManagementUpdateProviderOperation:                     []string{},
	ManagementUpdateWebhookOperation:                      []string{},
	ManagementVerifyDomainOperation:                       []string{},
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	// Sendmux API key. Use a root API key for Management API routes, or a mailbox credential for Mailbox
	// API routes. Obtain keys from the dashboard under API Keys.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
