// Code generated by ogen, DO NOT EDIT.
package management

type ManagementActivateProviderRes interface {
	managementActivateProviderRes()
}

type ManagementCreateDomainRes interface {
	managementCreateDomainRes()
}

type ManagementCreateMailboxKeyRes interface {
	managementCreateMailboxKeyRes()
}

type ManagementCreateMailboxRes interface {
	managementCreateMailboxRes()
}

type ManagementCreateProviderRes interface {
	managementCreateProviderRes()
}

type ManagementCreateSharedAmazonSesLimitRequestRes interface {
	managementCreateSharedAmazonSesLimitRequestRes()
}

type ManagementCreateWebhookRes interface {
	managementCreateWebhookRes()
}

type ManagementDeactivateProviderRes interface {
	managementDeactivateProviderRes()
}

type ManagementDeleteDomainRes interface {
	managementDeleteDomainRes()
}

type ManagementDeleteMailboxKeyRes interface {
	managementDeleteMailboxKeyRes()
}

type ManagementDeleteMailboxRes interface {
	managementDeleteMailboxRes()
}

type ManagementDeleteProviderRes interface {
	managementDeleteProviderRes()
}

type ManagementDeleteWebhookRes interface {
	managementDeleteWebhookRes()
}

type ManagementGetDeliveryPayloadRes interface {
	managementGetDeliveryPayloadRes()
}

type ManagementGetDomainFiltersRes interface {
	managementGetDomainFiltersRes()
}

type ManagementGetDomainRes interface {
	managementGetDomainRes()
}

type ManagementGetDomainZoneFileRes interface {
	managementGetDomainZoneFileRes()
}

type ManagementGetEmailLogRes interface {
	managementGetEmailLogRes()
}

type ManagementGetEmailMetricsRes interface {
	managementGetEmailMetricsRes()
}

type ManagementGetInboxLogRes interface {
	managementGetInboxLogRes()
}

type ManagementGetMailboxFiltersRes interface {
	managementGetMailboxFiltersRes()
}

type ManagementGetMailboxRes interface {
	managementGetMailboxRes()
}

type ManagementGetProviderRes interface {
	managementGetProviderRes()
}

type ManagementGetProviderStatsRes interface {
	managementGetProviderStatsRes()
}

type ManagementGetSpendSummaryRes interface {
	managementGetSpendSummaryRes()
}

type ManagementGetWebhookRes interface {
	managementGetWebhookRes()
}

type ManagementListBalanceRes interface {
	managementListBalanceRes()
}

type ManagementListDeliveryRes interface {
	managementListDeliveryRes()
}

type ManagementListDomainsRes interface {
	managementListDomainsRes()
}

type ManagementListEmailLogsRes interface {
	managementListEmailLogsRes()
}

type ManagementListInboxLogsRes interface {
	managementListInboxLogsRes()
}

type ManagementListMailboxesRes interface {
	managementListMailboxesRes()
}

type ManagementListProvidersRes interface {
	managementListProvidersRes()
}

type ManagementListTransactionsRes interface {
	managementListTransactionsRes()
}

type ManagementListWebhooksRes interface {
	managementListWebhooksRes()
}

type ManagementRequestSendingAccountLimitIncreaseRes interface {
	managementRequestSendingAccountLimitIncreaseRes()
}

type ManagementResumeMailboxRes interface {
	managementResumeMailboxRes()
}

type ManagementRotateWebhookSecretRes interface {
	managementRotateWebhookSecretRes()
}

type ManagementSetDomainFiltersRes interface {
	managementSetDomainFiltersRes()
}

type ManagementSetMailboxFiltersRes interface {
	managementSetMailboxFiltersRes()
}

type ManagementSuspendMailboxRes interface {
	managementSuspendMailboxRes()
}

type ManagementTestProviderRes interface {
	managementTestProviderRes()
}

type ManagementTestWebhookRes interface {
	managementTestWebhookRes()
}

type ManagementUpdateMailboxRes interface {
	managementUpdateMailboxRes()
}

type ManagementUpdateProviderRes interface {
	managementUpdateProviderRes()
}

type ManagementUpdateWebhookRes interface {
	managementUpdateWebhookRes()
}

type ManagementVerifyDomainRes interface {
	managementVerifyDomainRes()
}
