# coding: utf-8

"""
    Sendmux API

    Programmatic access to your Sendmux email infrastructure.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from sendmux_management.models.provider_status_counts import ProviderStatusCounts
from sendmux_management.models.provider_type_counts import ProviderTypeCounts
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProviderStats(BaseModel):
    """
    ProviderStats
    """ # noqa: E501
    active: Union[StrictFloat, StrictInt] = Field(description="Accounts with status 'active'")
    by_status: ProviderStatusCounts
    by_type: ProviderTypeCounts
    error: Union[StrictFloat, StrictInt] = Field(description="Accounts with status 'error'")
    inactive: Union[StrictFloat, StrictInt] = Field(description="Accounts with status 'inactive'")
    pending: Union[StrictFloat, StrictInt] = Field(description="Accounts with status 'pending'")
    total: Union[StrictFloat, StrictInt] = Field(description="Total number of sending accounts")
    __properties: ClassVar[List[str]] = ["active", "by_status", "by_type", "error", "inactive", "pending", "total"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProviderStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of by_status
        if self.by_status:
            _dict['by_status'] = self.by_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of by_type
        if self.by_type:
            _dict['by_type'] = self.by_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProviderStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "by_status": ProviderStatusCounts.from_dict(obj["by_status"]) if obj.get("by_status") is not None else None,
            "by_type": ProviderTypeCounts.from_dict(obj["by_type"]) if obj.get("by_type") is not None else None,
            "error": obj.get("error"),
            "inactive": obj.get("inactive"),
            "pending": obj.get("pending"),
            "total": obj.get("total")
        })
        return _obj


