# coding: utf-8

"""
    Sendmux API

    Programmatic access to your Sendmux email infrastructure.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SharedAmazonSesLimitRequest(BaseModel):
    """
    SharedAmazonSesLimitRequest
    """ # noqa: E501
    approved_daily_limit: Optional[Annotated[int, Field(strict=True, gt=0)]]
    created_at: StrictStr
    current_daily_limit: Annotated[int, Field(strict=True, ge=0)]
    current_daily_sent: Annotated[int, Field(strict=True, ge=0)]
    decided_at: Optional[StrictStr]
    decision_note: Optional[StrictStr]
    id: StrictStr
    status: StrictStr
    __properties: ClassVar[List[str]] = ["approved_daily_limit", "created_at", "current_daily_limit", "current_daily_sent", "decided_at", "decision_note", "id", "status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'approved', 'denied', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'approved', 'denied', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SharedAmazonSesLimitRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if approved_daily_limit (nullable) is None
        # and model_fields_set contains the field
        if self.approved_daily_limit is None and "approved_daily_limit" in self.model_fields_set:
            _dict['approved_daily_limit'] = None

        # set to None if decided_at (nullable) is None
        # and model_fields_set contains the field
        if self.decided_at is None and "decided_at" in self.model_fields_set:
            _dict['decided_at'] = None

        # set to None if decision_note (nullable) is None
        # and model_fields_set contains the field
        if self.decision_note is None and "decision_note" in self.model_fields_set:
            _dict['decision_note'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SharedAmazonSesLimitRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "approved_daily_limit": obj.get("approved_daily_limit"),
            "created_at": obj.get("created_at"),
            "current_daily_limit": obj.get("current_daily_limit"),
            "current_daily_sent": obj.get("current_daily_sent"),
            "decided_at": obj.get("decided_at"),
            "decision_note": obj.get("decision_note"),
            "id": obj.get("id"),
            "status": obj.get("status")
        })
        return _obj
