=begin
#Sendmux API

#Programmatic access to your Sendmux email infrastructure.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Sendmux::Management::Generated
  class DeliveryLogItem < ApiModelBase
    attr_accessor :attempts

    # ISO 8601 creation timestamp
    attr_accessor :created_at

    attr_accessor :from_email

    # Log public ID
    attr_accessor :id

    # Email Message-ID header
    attr_accessor :message_id

    # Provider public ID
    attr_accessor :provider_id

    # Provider display name
    attr_accessor :provider_name

    # ISO 8601 timestamp when email was sent
    attr_accessor :sent_at

    # The actual from address used for delivery after transformation. NULL if no transformation occurred or for older log entries.
    attr_accessor :sent_from_email

    attr_accessor :size_bytes

    attr_accessor :status

    attr_accessor :status_reason

    attr_accessor :subject

    attr_accessor :to_email

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'attempts' => :'attempts',
        :'created_at' => :'created_at',
        :'from_email' => :'from_email',
        :'id' => :'id',
        :'message_id' => :'message_id',
        :'provider_id' => :'provider_id',
        :'provider_name' => :'provider_name',
        :'sent_at' => :'sent_at',
        :'sent_from_email' => :'sent_from_email',
        :'size_bytes' => :'size_bytes',
        :'status' => :'status',
        :'status_reason' => :'status_reason',
        :'subject' => :'subject',
        :'to_email' => :'to_email'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'attempts' => :'Float',
        :'created_at' => :'String',
        :'from_email' => :'String',
        :'id' => :'String',
        :'message_id' => :'String',
        :'provider_id' => :'String',
        :'provider_name' => :'String',
        :'sent_at' => :'String',
        :'sent_from_email' => :'String',
        :'size_bytes' => :'Float',
        :'status' => :'String',
        :'status_reason' => :'String',
        :'subject' => :'String',
        :'to_email' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'from_email',
        :'message_id',
        :'provider_id',
        :'provider_name',
        :'sent_at',
        :'sent_from_email',
        :'size_bytes',
        :'status_reason',
        :'subject',
        :'to_email'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendmux::Management::Generated::DeliveryLogItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendmux::Management::Generated::DeliveryLogItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'attempts')
        self.attempts = attributes[:'attempts']
      else
        self.attempts = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'from_email')
        self.from_email = attributes[:'from_email']
      else
        self.from_email = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      else
        self.message_id = nil
      end

      if attributes.key?(:'provider_id')
        self.provider_id = attributes[:'provider_id']
      else
        self.provider_id = nil
      end

      if attributes.key?(:'provider_name')
        self.provider_name = attributes[:'provider_name']
      else
        self.provider_name = nil
      end

      if attributes.key?(:'sent_at')
        self.sent_at = attributes[:'sent_at']
      else
        self.sent_at = nil
      end

      if attributes.key?(:'sent_from_email')
        self.sent_from_email = attributes[:'sent_from_email']
      else
        self.sent_from_email = nil
      end

      if attributes.key?(:'size_bytes')
        self.size_bytes = attributes[:'size_bytes']
      else
        self.size_bytes = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'status_reason')
        self.status_reason = attributes[:'status_reason']
      else
        self.status_reason = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'to_email')
        self.to_email = attributes[:'to_email']
      else
        self.to_email = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @attempts.nil?
        invalid_properties.push('invalid value for "attempts", attempts cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @attempts.nil?
      return false if @created_at.nil?
      return false if @id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["pending", "sent", "failed", "rejected", "unknown_default_open_api"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] attempts Value to be assigned
    def attempts=(attempts)
      if attempts.nil?
        fail ArgumentError, 'attempts cannot be nil'
      end

      @attempts = attempts
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["pending", "sent", "failed", "rejected", "unknown_default_open_api"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          attempts == o.attempts &&
          created_at == o.created_at &&
          from_email == o.from_email &&
          id == o.id &&
          message_id == o.message_id &&
          provider_id == o.provider_id &&
          provider_name == o.provider_name &&
          sent_at == o.sent_at &&
          sent_from_email == o.sent_from_email &&
          size_bytes == o.size_bytes &&
          status == o.status &&
          status_reason == o.status_reason &&
          subject == o.subject &&
          to_email == o.to_email
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attempts, created_at, from_email, id, message_id, provider_id, provider_name, sent_at, sent_from_email, size_bytes, status, status_reason, subject, to_email].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
