=begin
#Sendmux API

#Programmatic access to your Sendmux email infrastructure.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Sendmux::Management::Generated
  class IncomingLogItem < ApiModelBase
    # Billable amount for this message in USD
    attr_accessor :amount

    # ISO 8601 usage bucket start
    attr_accessor :billing_bucket_start

    attr_accessor :event_type

    attr_accessor :from_email

    # Incoming log public ID
    attr_accessor :id

    attr_accessor :is_spam

    # Mailbox email address
    attr_accessor :mailbox_email

    # Mailbox public ID
    attr_accessor :mailbox_id

    # Message identifier when available
    attr_accessor :message_id

    # Identifier source when available
    attr_accessor :message_id_kind

    # ISO 8601 received timestamp
    attr_accessor :received_at

    attr_accessor :size_bytes

    attr_accessor :subject

    attr_accessor :to_emails

    # Per-message unit amount in USD
    attr_accessor :unit_amount

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'billing_bucket_start' => :'billing_bucket_start',
        :'event_type' => :'event_type',
        :'from_email' => :'from_email',
        :'id' => :'id',
        :'is_spam' => :'is_spam',
        :'mailbox_email' => :'mailbox_email',
        :'mailbox_id' => :'mailbox_id',
        :'message_id' => :'message_id',
        :'message_id_kind' => :'message_id_kind',
        :'received_at' => :'received_at',
        :'size_bytes' => :'size_bytes',
        :'subject' => :'subject',
        :'to_emails' => :'to_emails',
        :'unit_amount' => :'unit_amount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'String',
        :'billing_bucket_start' => :'String',
        :'event_type' => :'String',
        :'from_email' => :'String',
        :'id' => :'String',
        :'is_spam' => :'Boolean',
        :'mailbox_email' => :'String',
        :'mailbox_id' => :'String',
        :'message_id' => :'String',
        :'message_id_kind' => :'String',
        :'received_at' => :'String',
        :'size_bytes' => :'Float',
        :'subject' => :'String',
        :'to_emails' => :'Array<String>',
        :'unit_amount' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'from_email',
        :'mailbox_email',
        :'mailbox_id',
        :'message_id',
        :'message_id_kind',
        :'size_bytes',
        :'subject',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendmux::Management::Generated::IncomingLogItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendmux::Management::Generated::IncomingLogItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'billing_bucket_start')
        self.billing_bucket_start = attributes[:'billing_bucket_start']
      else
        self.billing_bucket_start = nil
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      else
        self.event_type = nil
      end

      if attributes.key?(:'from_email')
        self.from_email = attributes[:'from_email']
      else
        self.from_email = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'is_spam')
        self.is_spam = attributes[:'is_spam']
      else
        self.is_spam = nil
      end

      if attributes.key?(:'mailbox_email')
        self.mailbox_email = attributes[:'mailbox_email']
      else
        self.mailbox_email = nil
      end

      if attributes.key?(:'mailbox_id')
        self.mailbox_id = attributes[:'mailbox_id']
      else
        self.mailbox_id = nil
      end

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      else
        self.message_id = nil
      end

      if attributes.key?(:'message_id_kind')
        self.message_id_kind = attributes[:'message_id_kind']
      else
        self.message_id_kind = nil
      end

      if attributes.key?(:'received_at')
        self.received_at = attributes[:'received_at']
      else
        self.received_at = nil
      end

      if attributes.key?(:'size_bytes')
        self.size_bytes = attributes[:'size_bytes']
      else
        self.size_bytes = nil
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'to_emails')
        if (value = attributes[:'to_emails']).is_a?(Array)
          self.to_emails = value
        end
      else
        self.to_emails = nil
      end

      if attributes.key?(:'unit_amount')
        self.unit_amount = attributes[:'unit_amount']
      else
        self.unit_amount = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @billing_bucket_start.nil?
        invalid_properties.push('invalid value for "billing_bucket_start", billing_bucket_start cannot be nil.')
      end

      if @event_type.nil?
        invalid_properties.push('invalid value for "event_type", event_type cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @is_spam.nil?
        invalid_properties.push('invalid value for "is_spam", is_spam cannot be nil.')
      end

      if @received_at.nil?
        invalid_properties.push('invalid value for "received_at", received_at cannot be nil.')
      end

      if @to_emails.nil?
        invalid_properties.push('invalid value for "to_emails", to_emails cannot be nil.')
      end

      if @unit_amount.nil?
        invalid_properties.push('invalid value for "unit_amount", unit_amount cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @amount.nil?
      return false if @billing_bucket_start.nil?
      return false if @event_type.nil?
      event_type_validator = EnumAttributeValidator.new('String', ["message.received", "message.received.spam", "unknown_default_open_api"])
      return false unless event_type_validator.valid?(@event_type)
      return false if @id.nil?
      return false if @is_spam.nil?
      return false if @received_at.nil?
      return false if @to_emails.nil?
      return false if @unit_amount.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] billing_bucket_start Value to be assigned
    def billing_bucket_start=(billing_bucket_start)
      if billing_bucket_start.nil?
        fail ArgumentError, 'billing_bucket_start cannot be nil'
      end

      @billing_bucket_start = billing_bucket_start
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] event_type Object to be assigned
    def event_type=(event_type)
      validator = EnumAttributeValidator.new('String', ["message.received", "message.received.spam", "unknown_default_open_api"])
      unless validator.valid?(event_type)
        fail ArgumentError, "invalid value for \"event_type\", must be one of #{validator.allowable_values}."
      end
      @event_type = event_type
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] is_spam Value to be assigned
    def is_spam=(is_spam)
      if is_spam.nil?
        fail ArgumentError, 'is_spam cannot be nil'
      end

      @is_spam = is_spam
    end

    # Custom attribute writer method with validation
    # @param [Object] received_at Value to be assigned
    def received_at=(received_at)
      if received_at.nil?
        fail ArgumentError, 'received_at cannot be nil'
      end

      @received_at = received_at
    end

    # Custom attribute writer method with validation
    # @param [Object] to_emails Value to be assigned
    def to_emails=(to_emails)
      if to_emails.nil?
        fail ArgumentError, 'to_emails cannot be nil'
      end

      @to_emails = to_emails
    end

    # Custom attribute writer method with validation
    # @param [Object] unit_amount Value to be assigned
    def unit_amount=(unit_amount)
      if unit_amount.nil?
        fail ArgumentError, 'unit_amount cannot be nil'
      end

      @unit_amount = unit_amount
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          billing_bucket_start == o.billing_bucket_start &&
          event_type == o.event_type &&
          from_email == o.from_email &&
          id == o.id &&
          is_spam == o.is_spam &&
          mailbox_email == o.mailbox_email &&
          mailbox_id == o.mailbox_id &&
          message_id == o.message_id &&
          message_id_kind == o.message_id_kind &&
          received_at == o.received_at &&
          size_bytes == o.size_bytes &&
          subject == o.subject &&
          to_emails == o.to_emails &&
          unit_amount == o.unit_amount
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, billing_bucket_start, event_type, from_email, id, is_spam, mailbox_email, mailbox_id, message_id, message_id_kind, received_at, size_bytes, subject, to_emails, unit_amount].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
