=begin
#Sendmux API

#Programmatic access to your Sendmux email infrastructure.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Sendmux::Management::Generated
  class MailboxDomain < ApiModelBase
    # ISO 8601 creation timestamp
    attr_accessor :created_at

    attr_accessor :dns_records

    # Fully qualified domain name
    attr_accessor :domain

    # Public ID
    attr_accessor :id

    # Active mailboxes currently using this domain
    attr_accessor :mailbox_count

    # `send_only` verifies outbound DNS only. `send_receive` also verifies MX records and can host mailboxes.
    attr_accessor :mode

    # Amazon SES DKIM status (pending/success/failed/temporary_failure/not_started)
    attr_accessor :ses_dkim_status

    # Current verification state
    attr_accessor :verification_status

    # ISO 8601 timestamp of last successful verification
    attr_accessor :verified_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_at' => :'created_at',
        :'dns_records' => :'dns_records',
        :'domain' => :'domain',
        :'id' => :'id',
        :'mailbox_count' => :'mailbox_count',
        :'mode' => :'mode',
        :'ses_dkim_status' => :'ses_dkim_status',
        :'verification_status' => :'verification_status',
        :'verified_at' => :'verified_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created_at' => :'String',
        :'dns_records' => :'MailboxDomainDnsRecords',
        :'domain' => :'String',
        :'id' => :'String',
        :'mailbox_count' => :'Integer',
        :'mode' => :'String',
        :'ses_dkim_status' => :'String',
        :'verification_status' => :'String',
        :'verified_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'ses_dkim_status',
        :'verified_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendmux::Management::Generated::MailboxDomain` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendmux::Management::Generated::MailboxDomain`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'dns_records')
        self.dns_records = attributes[:'dns_records']
      else
        self.dns_records = nil
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'mailbox_count')
        self.mailbox_count = attributes[:'mailbox_count']
      else
        self.mailbox_count = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'ses_dkim_status')
        self.ses_dkim_status = attributes[:'ses_dkim_status']
      else
        self.ses_dkim_status = nil
      end

      if attributes.key?(:'verification_status')
        self.verification_status = attributes[:'verification_status']
      else
        self.verification_status = nil
      end

      if attributes.key?(:'verified_at')
        self.verified_at = attributes[:'verified_at']
      else
        self.verified_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @dns_records.nil?
        invalid_properties.push('invalid value for "dns_records", dns_records cannot be nil.')
      end

      if @domain.nil?
        invalid_properties.push('invalid value for "domain", domain cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @mailbox_count.nil?
        invalid_properties.push('invalid value for "mailbox_count", mailbox_count cannot be nil.')
      end

      if @mailbox_count < 0
        invalid_properties.push('invalid value for "mailbox_count", must be greater than or equal to 0.')
      end

      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      if @verification_status.nil?
        invalid_properties.push('invalid value for "verification_status", verification_status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @created_at.nil?
      return false if @dns_records.nil?
      return false if @domain.nil?
      return false if @id.nil?
      return false if @mailbox_count.nil?
      return false if @mailbox_count < 0
      return false if @mode.nil?
      mode_validator = EnumAttributeValidator.new('String', ["send_only", "send_receive", "unknown_default_open_api"])
      return false unless mode_validator.valid?(@mode)
      return false if @verification_status.nil?
      verification_status_validator = EnumAttributeValidator.new('String', ["pending", "verified", "failed", "unknown_default_open_api"])
      return false unless verification_status_validator.valid?(@verification_status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] dns_records Value to be assigned
    def dns_records=(dns_records)
      if dns_records.nil?
        fail ArgumentError, 'dns_records cannot be nil'
      end

      @dns_records = dns_records
    end

    # Custom attribute writer method with validation
    # @param [Object] domain Value to be assigned
    def domain=(domain)
      if domain.nil?
        fail ArgumentError, 'domain cannot be nil'
      end

      @domain = domain
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] mailbox_count Value to be assigned
    def mailbox_count=(mailbox_count)
      if mailbox_count.nil?
        fail ArgumentError, 'mailbox_count cannot be nil'
      end

      if mailbox_count < 0
        fail ArgumentError, 'invalid value for "mailbox_count", must be greater than or equal to 0.'
      end

      @mailbox_count = mailbox_count
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] mode Object to be assigned
    def mode=(mode)
      validator = EnumAttributeValidator.new('String', ["send_only", "send_receive", "unknown_default_open_api"])
      unless validator.valid?(mode)
        fail ArgumentError, "invalid value for \"mode\", must be one of #{validator.allowable_values}."
      end
      @mode = mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] verification_status Object to be assigned
    def verification_status=(verification_status)
      validator = EnumAttributeValidator.new('String', ["pending", "verified", "failed", "unknown_default_open_api"])
      unless validator.valid?(verification_status)
        fail ArgumentError, "invalid value for \"verification_status\", must be one of #{validator.allowable_values}."
      end
      @verification_status = verification_status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          dns_records == o.dns_records &&
          domain == o.domain &&
          id == o.id &&
          mailbox_count == o.mailbox_count &&
          mode == o.mode &&
          ses_dkim_status == o.ses_dkim_status &&
          verification_status == o.verification_status &&
          verified_at == o.verified_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created_at, dns_records, domain, id, mailbox_count, mode, ses_dkim_status, verification_status, verified_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
