// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";

export default class MailboxGetFolderChangesCommand extends OperationCommand {
  static description = operations.mailboxGetFolderChanges.description;
  static operation = operations.mailboxGetFolderChanges;
}
