// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";

export default class MailboxGetMessageAttachmentCommand extends OperationCommand {
  static description = operations.mailboxGetMessageAttachment.description;
  static operation = operations.mailboxGetMessageAttachment;
}
