// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";

export default class MailboxQueryMessageChangesCommand extends OperationCommand {
  static description = operations.mailboxQueryMessageChanges.description;
  static operation = operations.mailboxQueryMessageChanges;
}
