// This file is generated by scripts/generate-cli.mjs

import { Flags } from "@oclif/core";
import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";
import { operationFlags } from "../../operation-flags.js";

export default class MailboxStreamEventsCommand extends OperationCommand {
  static description = operations.mailboxStreamEvents.description;
  static flags = {
    ...operationFlags,
    follow: Flags.boolean({
      description: "Keep streaming mailbox events until the stream closes or the process is interrupted. Emits one JSON object per line.",
    }),
  };
  static operation = operations.mailboxStreamEvents;
}
