// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";

export default class ManagementCreateProviderCommand extends OperationCommand {
  static description = operations.managementCreateProvider.description;
  static operation = operations.managementCreateProvider;
}
