// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";

export default class ManagementGetInboxLogCommand extends OperationCommand {
  static description = operations.managementGetInboxLog.description;
  static operation = operations.managementGetInboxLog;
}
