// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../generated/operations.js";
import { OperationCommand } from "../../operation-command.js";

export default class ManagementTestWebhookCommand extends OperationCommand {
  static description = operations.managementTestWebhook.description;
  static operation = operations.managementTestWebhook;
}
