=begin
#Sendmux API

#Programmatic access to your Sendmux email infrastructure.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Sendmux::Mailbox::Generated
  class CreateMailboxDraftAttachmentsInner < ApiModelBase
    # An attachment uploaded to this mailbox.
    attr_accessor :blob_id

    # Content ID referenced by an inline image.
    attr_accessor :content_id

    # Attachment media type.
    attr_accessor :content_type

    # Whether the attachment appears within the message.
    attr_accessor :disposition

    # Attachment filename.
    attr_accessor :filename

    # Attachment size in bytes; verified when saved.
    attr_accessor :size_bytes

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'blob_id' => :'blob_id',
        :'content_id' => :'content_id',
        :'content_type' => :'content_type',
        :'disposition' => :'disposition',
        :'filename' => :'filename',
        :'size_bytes' => :'size_bytes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'blob_id' => :'String',
        :'content_id' => :'String',
        :'content_type' => :'String',
        :'disposition' => :'String',
        :'filename' => :'String',
        :'size_bytes' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendmux::Mailbox::Generated::CreateMailboxDraftAttachmentsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendmux::Mailbox::Generated::CreateMailboxDraftAttachmentsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'blob_id')
        self.blob_id = attributes[:'blob_id']
      else
        self.blob_id = nil
      end

      if attributes.key?(:'content_id')
        self.content_id = attributes[:'content_id']
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      else
        self.content_type = nil
      end

      if attributes.key?(:'disposition')
        self.disposition = attributes[:'disposition']
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      else
        self.filename = nil
      end

      if attributes.key?(:'size_bytes')
        self.size_bytes = attributes[:'size_bytes']
      else
        self.size_bytes = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @blob_id.nil?
        invalid_properties.push('invalid value for "blob_id", blob_id cannot be nil.')
      end

      if @blob_id.to_s.length > 255
        invalid_properties.push('invalid value for "blob_id", the character length must be smaller than or equal to 255.')
      end

      if @blob_id.to_s.length < 1
        invalid_properties.push('invalid value for "blob_id", the character length must be greater than or equal to 1.')
      end

      if !@content_id.nil? && @content_id.to_s.length > 998
        invalid_properties.push('invalid value for "content_id", the character length must be smaller than or equal to 998.')
      end

      if !@content_id.nil? && @content_id.to_s.length < 1
        invalid_properties.push('invalid value for "content_id", the character length must be greater than or equal to 1.')
      end

      if @content_type.nil?
        invalid_properties.push('invalid value for "content_type", content_type cannot be nil.')
      end

      if @content_type.to_s.length > 255
        invalid_properties.push('invalid value for "content_type", the character length must be smaller than or equal to 255.')
      end

      if @content_type.to_s.length < 1
        invalid_properties.push('invalid value for "content_type", the character length must be greater than or equal to 1.')
      end

      if @filename.nil?
        invalid_properties.push('invalid value for "filename", filename cannot be nil.')
      end

      if @filename.to_s.length > 255
        invalid_properties.push('invalid value for "filename", the character length must be smaller than or equal to 255.')
      end

      if @filename.to_s.length < 1
        invalid_properties.push('invalid value for "filename", the character length must be greater than or equal to 1.')
      end

      if @size_bytes.nil?
        invalid_properties.push('invalid value for "size_bytes", size_bytes cannot be nil.')
      end

      if @size_bytes > 7500000
        invalid_properties.push('invalid value for "size_bytes", must be smaller than or equal to 7500000.')
      end

      if @size_bytes < 0
        invalid_properties.push('invalid value for "size_bytes", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @blob_id.nil?
      return false if @blob_id.to_s.length > 255
      return false if @blob_id.to_s.length < 1
      return false if !@content_id.nil? && @content_id.to_s.length > 998
      return false if !@content_id.nil? && @content_id.to_s.length < 1
      return false if @content_type.nil?
      return false if @content_type.to_s.length > 255
      return false if @content_type.to_s.length < 1
      disposition_validator = EnumAttributeValidator.new('String', ["attachment", "inline", "unknown_default_open_api"])
      return false unless disposition_validator.valid?(@disposition)
      return false if @filename.nil?
      return false if @filename.to_s.length > 255
      return false if @filename.to_s.length < 1
      return false if @size_bytes.nil?
      return false if @size_bytes > 7500000
      return false if @size_bytes < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] blob_id Value to be assigned
    def blob_id=(blob_id)
      if blob_id.nil?
        fail ArgumentError, 'blob_id cannot be nil'
      end

      if blob_id.to_s.length > 255
        fail ArgumentError, 'invalid value for "blob_id", the character length must be smaller than or equal to 255.'
      end

      if blob_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "blob_id", the character length must be greater than or equal to 1.'
      end

      @blob_id = blob_id
    end

    # Custom attribute writer method with validation
    # @param [Object] content_id Value to be assigned
    def content_id=(content_id)
      if content_id.nil?
        fail ArgumentError, 'content_id cannot be nil'
      end

      if content_id.to_s.length > 998
        fail ArgumentError, 'invalid value for "content_id", the character length must be smaller than or equal to 998.'
      end

      if content_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "content_id", the character length must be greater than or equal to 1.'
      end

      @content_id = content_id
    end

    # Custom attribute writer method with validation
    # @param [Object] content_type Value to be assigned
    def content_type=(content_type)
      if content_type.nil?
        fail ArgumentError, 'content_type cannot be nil'
      end

      if content_type.to_s.length > 255
        fail ArgumentError, 'invalid value for "content_type", the character length must be smaller than or equal to 255.'
      end

      if content_type.to_s.length < 1
        fail ArgumentError, 'invalid value for "content_type", the character length must be greater than or equal to 1.'
      end

      @content_type = content_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] disposition Object to be assigned
    def disposition=(disposition)
      validator = EnumAttributeValidator.new('String', ["attachment", "inline", "unknown_default_open_api"])
      unless validator.valid?(disposition)
        fail ArgumentError, "invalid value for \"disposition\", must be one of #{validator.allowable_values}."
      end
      @disposition = disposition
    end

    # Custom attribute writer method with validation
    # @param [Object] filename Value to be assigned
    def filename=(filename)
      if filename.nil?
        fail ArgumentError, 'filename cannot be nil'
      end

      if filename.to_s.length > 255
        fail ArgumentError, 'invalid value for "filename", the character length must be smaller than or equal to 255.'
      end

      if filename.to_s.length < 1
        fail ArgumentError, 'invalid value for "filename", the character length must be greater than or equal to 1.'
      end

      @filename = filename
    end

    # Custom attribute writer method with validation
    # @param [Object] size_bytes Value to be assigned
    def size_bytes=(size_bytes)
      if size_bytes.nil?
        fail ArgumentError, 'size_bytes cannot be nil'
      end

      if size_bytes > 7500000
        fail ArgumentError, 'invalid value for "size_bytes", must be smaller than or equal to 7500000.'
      end

      if size_bytes < 0
        fail ArgumentError, 'invalid value for "size_bytes", must be greater than or equal to 0.'
      end

      @size_bytes = size_bytes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          blob_id == o.blob_id &&
          content_id == o.content_id &&
          content_type == o.content_type &&
          disposition == o.disposition &&
          filename == o.filename &&
          size_bytes == o.size_bytes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [blob_id, content_id, content_type, disposition, filename, size_bytes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
