=begin
#Sendmux API

#Programmatic access to your Sendmux email infrastructure.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Sendmux::Mailbox::Generated
  class MailboxQuota < ApiModelBase
    attr_accessor :description

    attr_accessor :hard_limit

    # Quota ID
    attr_accessor :id

    attr_accessor :name

    attr_accessor :resource_type

    attr_accessor :scope

    attr_accessor :soft_limit

    attr_accessor :types

    attr_accessor :used

    attr_accessor :warn_limit

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'description' => :'description',
        :'hard_limit' => :'hard_limit',
        :'id' => :'id',
        :'name' => :'name',
        :'resource_type' => :'resource_type',
        :'scope' => :'scope',
        :'soft_limit' => :'soft_limit',
        :'types' => :'types',
        :'used' => :'used',
        :'warn_limit' => :'warn_limit'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'description' => :'String',
        :'hard_limit' => :'Integer',
        :'id' => :'String',
        :'name' => :'String',
        :'resource_type' => :'String',
        :'scope' => :'String',
        :'soft_limit' => :'Integer',
        :'types' => :'Array<String>',
        :'used' => :'Integer',
        :'warn_limit' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'soft_limit',
        :'warn_limit'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendmux::Mailbox::Generated::MailboxQuota` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendmux::Mailbox::Generated::MailboxQuota`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'hard_limit')
        self.hard_limit = attributes[:'hard_limit']
      else
        self.hard_limit = nil
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'resource_type')
        self.resource_type = attributes[:'resource_type']
      else
        self.resource_type = nil
      end

      if attributes.key?(:'scope')
        self.scope = attributes[:'scope']
      else
        self.scope = nil
      end

      if attributes.key?(:'soft_limit')
        self.soft_limit = attributes[:'soft_limit']
      else
        self.soft_limit = nil
      end

      if attributes.key?(:'types')
        if (value = attributes[:'types']).is_a?(Array)
          self.types = value
        end
      else
        self.types = nil
      end

      if attributes.key?(:'used')
        self.used = attributes[:'used']
      else
        self.used = nil
      end

      if attributes.key?(:'warn_limit')
        self.warn_limit = attributes[:'warn_limit']
      else
        self.warn_limit = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @hard_limit.nil?
        invalid_properties.push('invalid value for "hard_limit", hard_limit cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @resource_type.nil?
        invalid_properties.push('invalid value for "resource_type", resource_type cannot be nil.')
      end

      if @scope.nil?
        invalid_properties.push('invalid value for "scope", scope cannot be nil.')
      end

      if @types.nil?
        invalid_properties.push('invalid value for "types", types cannot be nil.')
      end

      if @used.nil?
        invalid_properties.push('invalid value for "used", used cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @hard_limit.nil?
      return false if @id.nil?
      return false if @name.nil?
      return false if @resource_type.nil?
      return false if @scope.nil?
      return false if @types.nil?
      return false if @used.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] hard_limit Value to be assigned
    def hard_limit=(hard_limit)
      if hard_limit.nil?
        fail ArgumentError, 'hard_limit cannot be nil'
      end

      @hard_limit = hard_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] resource_type Value to be assigned
    def resource_type=(resource_type)
      if resource_type.nil?
        fail ArgumentError, 'resource_type cannot be nil'
      end

      @resource_type = resource_type
    end

    # Custom attribute writer method with validation
    # @param [Object] scope Value to be assigned
    def scope=(scope)
      if scope.nil?
        fail ArgumentError, 'scope cannot be nil'
      end

      @scope = scope
    end

    # Custom attribute writer method with validation
    # @param [Object] types Value to be assigned
    def types=(types)
      if types.nil?
        fail ArgumentError, 'types cannot be nil'
      end

      @types = types
    end

    # Custom attribute writer method with validation
    # @param [Object] used Value to be assigned
    def used=(used)
      if used.nil?
        fail ArgumentError, 'used cannot be nil'
      end

      @used = used
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          description == o.description &&
          hard_limit == o.hard_limit &&
          id == o.id &&
          name == o.name &&
          resource_type == o.resource_type &&
          scope == o.scope &&
          soft_limit == o.soft_limit &&
          types == o.types &&
          used == o.used &&
          warn_limit == o.warn_limit
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [description, hard_limit, id, name, resource_type, scope, soft_limit, types, used, warn_limit].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
