// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../../generated/operations.js";
import { OperationCommand } from "../../../operation-command.js";

export default class ManagementGetDomainCommand extends OperationCommand {
  static description = operations.managementGetDomain.description;
  static operation = operations.managementGetDomain;
}
