// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../../generated/operations.js";
import { OperationCommand } from "../../../operation-command.js";

export default class ManagementListDomainsCommand extends OperationCommand {
  static description = operations.managementListDomains.description;
  static operation = operations.managementListDomains;
}
