=begin
#Sendmux API

#Programmatic access to your Sendmux email infrastructure.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'sendmux_management_generated/api_client'
require 'sendmux_management_generated/api_error'
require 'sendmux_management_generated/api_model_base'
require 'sendmux_management_generated/version'
require 'sendmux_management_generated/configuration'

# Models
require 'sendmux_management_generated/models/api_error_detail'
require 'sendmux_management_generated/models/api_error_error'
require 'sendmux_management_generated/models/api_error_meta'
require 'sendmux_management_generated/models/api_error_response'
require 'sendmux_management_generated/models/balance'
require 'sendmux_management_generated/models/balance_auto_topup'
require 'sendmux_management_generated/models/balance_response'
require 'sendmux_management_generated/models/cursor_pagination'
require 'sendmux_management_generated/models/delivery_log_item'
require 'sendmux_management_generated/models/delivery_log_item_cursor_list_response'
require 'sendmux_management_generated/models/delivery_log_item_response'
require 'sendmux_management_generated/models/domain_deleted_response'
require 'sendmux_management_generated/models/domain_deleted_response_all_of_data'
require 'sendmux_management_generated/models/domain_item_cursor_list_response'
require 'sendmux_management_generated/models/domain_item_response'
require 'sendmux_management_generated/models/domain_verify_response'
require 'sendmux_management_generated/models/email_metrics'
require 'sendmux_management_generated/models/email_metrics_comparison'
require 'sendmux_management_generated/models/email_metrics_comparison_change_pct'
require 'sendmux_management_generated/models/email_metrics_response'
require 'sendmux_management_generated/models/email_metrics_summary'
require 'sendmux_management_generated/models/email_metrics_timeseries_inner'
require 'sendmux_management_generated/models/filter_rule'
require 'sendmux_management_generated/models/filter_state'
require 'sendmux_management_generated/models/filter_state_response'
require 'sendmux_management_generated/models/incoming_log_item'
require 'sendmux_management_generated/models/incoming_log_item_cursor_list_response'
require 'sendmux_management_generated/models/incoming_log_item_response'
require 'sendmux_management_generated/models/mailbox'
require 'sendmux_management_generated/models/mailbox_app_password_result'
require 'sendmux_management_generated/models/mailbox_app_password_result_credential'
require 'sendmux_management_generated/models/mailbox_app_password_result_response'
require 'sendmux_management_generated/models/mailbox_availability_reason'
require 'sendmux_management_generated/models/mailbox_availability_response'
require 'sendmux_management_generated/models/mailbox_availability_result'
require 'sendmux_management_generated/models/mailbox_create_result'
require 'sendmux_management_generated/models/mailbox_create_result_response'
require 'sendmux_management_generated/models/mailbox_credential'
require 'sendmux_management_generated/models/mailbox_deleted_response'
require 'sendmux_management_generated/models/mailbox_domain'
require 'sendmux_management_generated/models/mailbox_domain_dns_records'
require 'sendmux_management_generated/models/mailbox_domain_mx_record'
require 'sendmux_management_generated/models/mailbox_domain_name_value_record'
require 'sendmux_management_generated/models/mailbox_domain_verify_checks'
require 'sendmux_management_generated/models/mailbox_domain_verify_result'
require 'sendmux_management_generated/models/mailbox_item_cursor_list_response'
require 'sendmux_management_generated/models/mailbox_item_response'
require 'sendmux_management_generated/models/mailbox_key_deleted_response'
require 'sendmux_management_generated/models/mailbox_send_scope'
require 'sendmux_management_generated/models/management_create_domain_request'
require 'sendmux_management_generated/models/management_create_mailbox_key_request'
require 'sendmux_management_generated/models/management_create_mailbox_request'
require 'sendmux_management_generated/models/management_create_mailbox_request_send_scope'
require 'sendmux_management_generated/models/management_test_webhook200_response'
require 'sendmux_management_generated/models/management_update_domain_request'
require 'sendmux_management_generated/models/provider_allowed_actions'
require 'sendmux_management_generated/models/provider_create_body'
require 'sendmux_management_generated/models/provider_create_body_quotas'
require 'sendmux_management_generated/models/provider_create_body_quotas_per_day'
require 'sendmux_management_generated/models/provider_create_body_quotas_per_day_any_of'
require 'sendmux_management_generated/models/provider_deleted'
require 'sendmux_management_generated/models/provider_deleted_response'
require 'sendmux_management_generated/models/provider_item'
require 'sendmux_management_generated/models/provider_item_cursor_list_response'
require 'sendmux_management_generated/models/provider_item_response'
require 'sendmux_management_generated/models/provider_limits'
require 'sendmux_management_generated/models/provider_limits_response'
require 'sendmux_management_generated/models/provider_quota_range'
require 'sendmux_management_generated/models/provider_quotas'
require 'sendmux_management_generated/models/provider_stats'
require 'sendmux_management_generated/models/provider_stats_response'
require 'sendmux_management_generated/models/provider_status_counts'
require 'sendmux_management_generated/models/provider_test_result'
require 'sendmux_management_generated/models/provider_test_result_response'
require 'sendmux_management_generated/models/provider_type_counts'
require 'sendmux_management_generated/models/provider_update_body'
require 'sendmux_management_generated/models/provider_usage'
require 'sendmux_management_generated/models/provider_usage_item'
require 'sendmux_management_generated/models/provider_usage_response'
require 'sendmux_management_generated/models/resource_limit_snapshot'
require 'sendmux_management_generated/models/response_meta'
require 'sendmux_management_generated/models/sending_account_limit_request'
require 'sendmux_management_generated/models/sending_account_limit_request_response'
require 'sendmux_management_generated/models/set_filter_state_body'
require 'sendmux_management_generated/models/shared_amazon_ses_limit'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request_cancel'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request_cancel_response'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request_create'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request_create_response'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request_page'
require 'sendmux_management_generated/models/shared_amazon_ses_limit_request_page_response'
require 'sendmux_management_generated/models/spend_summary'
require 'sendmux_management_generated/models/spend_summary_response'
require 'sendmux_management_generated/models/success_envelope'
require 'sendmux_management_generated/models/transaction'
require 'sendmux_management_generated/models/transaction_cursor_list_response'
require 'sendmux_management_generated/models/update_mailbox_body'
require 'sendmux_management_generated/models/update_mailbox_body_send_scope'
require 'sendmux_management_generated/models/webhook_create_body'
require 'sendmux_management_generated/models/webhook_deleted_response'
require 'sendmux_management_generated/models/webhook_delivery_attempt'
require 'sendmux_management_generated/models/webhook_delivery_attempt_cursor_list_response'
require 'sendmux_management_generated/models/webhook_delivery_payload'
require 'sendmux_management_generated/models/webhook_delivery_payload_response'
require 'sendmux_management_generated/models/webhook_event_data'
require 'sendmux_management_generated/models/webhook_event_payload'
require 'sendmux_management_generated/models/webhook_filters'
require 'sendmux_management_generated/models/webhook_subscription'
require 'sendmux_management_generated/models/webhook_subscription_cursor_list_response'
require 'sendmux_management_generated/models/webhook_subscription_response'
require 'sendmux_management_generated/models/webhook_subscription_with_secret'
require 'sendmux_management_generated/models/webhook_subscription_with_secret_response'
require 'sendmux_management_generated/models/webhook_test_response'
require 'sendmux_management_generated/models/webhook_update_body'

# APIs
require 'sendmux_management_generated/api/billing_api'
require 'sendmux_management_generated/api/domain_filters_api'
require 'sendmux_management_generated/api/domains_api'
require 'sendmux_management_generated/api/emails_api'
require 'sendmux_management_generated/api/inboxes_api'
require 'sendmux_management_generated/api/mailbox_filters_api'
require 'sendmux_management_generated/api/mailboxes_api'
require 'sendmux_management_generated/api/sending_accounts_api'
require 'sendmux_management_generated/api/webhooks_api'

module Sendmux::Management::Generated
  class << self
    # Customize default settings for the SDK using block.
    #   Sendmux::Management::Generated.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
