=begin
#Sendmux Sending API

#Send emails programmatically via the Sendmux email infrastructure. Every response carries an `X-Request-Id` header; errors include a `retryable` flag. 429 and 503 responses include `Retry-After`. Mutating endpoints accept an `Idempotency-Key` header for safe retries.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Sendmux::Sending::Generated
  class EmailSendRequest < ApiModelBase
    # File attachments (max 10). Use attachment_id refs for uploaded files.
    attr_accessor :attachments

    # BCC recipients (max 100)
    attr_accessor :bcc

    # CC recipients (max 100)
    attr_accessor :cc

    # Custom X-* headers to include in the email
    attr_accessor :custom_headers

    attr_accessor :from

    # HTML email content (max 25MB)
    attr_accessor :html_body

    # Reply-To address
    attr_accessor :reply_to

    # Envelope sender for VERP support
    attr_accessor :return_path

    # Email subject line (max 998 chars, RFC 5322)
    attr_accessor :subject

    # Plain text alternative (max 25MB)
    attr_accessor :text_body

    # Primary recipient
    attr_accessor :to

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'attachments' => :'attachments',
        :'bcc' => :'bcc',
        :'cc' => :'cc',
        :'custom_headers' => :'custom_headers',
        :'from' => :'from',
        :'html_body' => :'html_body',
        :'reply_to' => :'reply_to',
        :'return_path' => :'return_path',
        :'subject' => :'subject',
        :'text_body' => :'text_body',
        :'to' => :'to'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'attachments' => :'Array<Attachment>',
        :'bcc' => :'Array<Recipient>',
        :'cc' => :'Array<Recipient>',
        :'custom_headers' => :'Hash<String, String>',
        :'from' => :'Address',
        :'html_body' => :'String',
        :'reply_to' => :'Address',
        :'return_path' => :'String',
        :'subject' => :'String',
        :'text_body' => :'String',
        :'to' => :'Address'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Sendmux::Sending::Generated::EmailSendRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Sendmux::Sending::Generated::EmailSendRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'attachments')
        if (value = attributes[:'attachments']).is_a?(Array)
          self.attachments = value
        end
      end

      if attributes.key?(:'bcc')
        if (value = attributes[:'bcc']).is_a?(Array)
          self.bcc = value
        end
      end

      if attributes.key?(:'cc')
        if (value = attributes[:'cc']).is_a?(Array)
          self.cc = value
        end
      end

      if attributes.key?(:'custom_headers')
        if (value = attributes[:'custom_headers']).is_a?(Hash)
          self.custom_headers = value
        end
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'html_body')
        self.html_body = attributes[:'html_body']
      else
        self.html_body = nil
      end

      if attributes.key?(:'reply_to')
        self.reply_to = attributes[:'reply_to']
      end

      if attributes.key?(:'return_path')
        self.return_path = attributes[:'return_path']
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      else
        self.subject = nil
      end

      if attributes.key?(:'text_body')
        self.text_body = attributes[:'text_body']
      end

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      else
        self.to = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@attachments.nil? && @attachments.length > 10
        invalid_properties.push('invalid value for "attachments", number of items must be less than or equal to 10.')
      end

      if !@bcc.nil? && @bcc.length > 100
        invalid_properties.push('invalid value for "bcc", number of items must be less than or equal to 100.')
      end

      if !@cc.nil? && @cc.length > 100
        invalid_properties.push('invalid value for "cc", number of items must be less than or equal to 100.')
      end

      if @from.nil?
        invalid_properties.push('invalid value for "from", from cannot be nil.')
      end

      if @html_body.nil?
        invalid_properties.push('invalid value for "html_body", html_body cannot be nil.')
      end

      if @html_body.to_s.length > 26214400
        invalid_properties.push('invalid value for "html_body", the character length must be smaller than or equal to 26214400.')
      end

      if @html_body.to_s.length < 1
        invalid_properties.push('invalid value for "html_body", the character length must be greater than or equal to 1.')
      end

      if !@return_path.nil? && @return_path.to_s.length > 254
        invalid_properties.push('invalid value for "return_path", the character length must be smaller than or equal to 254.')
      end

      if @subject.nil?
        invalid_properties.push('invalid value for "subject", subject cannot be nil.')
      end

      if @subject.to_s.length > 998
        invalid_properties.push('invalid value for "subject", the character length must be smaller than or equal to 998.')
      end

      if @subject.to_s.length < 1
        invalid_properties.push('invalid value for "subject", the character length must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^[^\r\n]*$/)
      if @subject !~ pattern
        invalid_properties.push("invalid value for \"subject\", must conform to the pattern #{pattern}.")
      end

      if !@text_body.nil? && @text_body.to_s.length > 26214400
        invalid_properties.push('invalid value for "text_body", the character length must be smaller than or equal to 26214400.')
      end

      if @to.nil?
        invalid_properties.push('invalid value for "to", to cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@attachments.nil? && @attachments.length > 10
      return false if !@bcc.nil? && @bcc.length > 100
      return false if !@cc.nil? && @cc.length > 100
      return false if @from.nil?
      return false if @html_body.nil?
      return false if @html_body.to_s.length > 26214400
      return false if @html_body.to_s.length < 1
      return false if !@return_path.nil? && @return_path.to_s.length > 254
      return false if @subject.nil?
      return false if @subject.to_s.length > 998
      return false if @subject.to_s.length < 1
      return false if @subject !~ Regexp.new(/^[^\r\n]*$/)
      return false if !@text_body.nil? && @text_body.to_s.length > 26214400
      return false if @to.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] attachments Value to be assigned
    def attachments=(attachments)
      if attachments.nil?
        fail ArgumentError, 'attachments cannot be nil'
      end

      if attachments.length > 10
        fail ArgumentError, 'invalid value for "attachments", number of items must be less than or equal to 10.'
      end

      @attachments = attachments
    end

    # Custom attribute writer method with validation
    # @param [Object] bcc Value to be assigned
    def bcc=(bcc)
      if bcc.nil?
        fail ArgumentError, 'bcc cannot be nil'
      end

      if bcc.length > 100
        fail ArgumentError, 'invalid value for "bcc", number of items must be less than or equal to 100.'
      end

      @bcc = bcc
    end

    # Custom attribute writer method with validation
    # @param [Object] cc Value to be assigned
    def cc=(cc)
      if cc.nil?
        fail ArgumentError, 'cc cannot be nil'
      end

      if cc.length > 100
        fail ArgumentError, 'invalid value for "cc", number of items must be less than or equal to 100.'
      end

      @cc = cc
    end

    # Custom attribute writer method with validation
    # @param [Object] from Value to be assigned
    def from=(from)
      if from.nil?
        fail ArgumentError, 'from cannot be nil'
      end

      @from = from
    end

    # Custom attribute writer method with validation
    # @param [Object] html_body Value to be assigned
    def html_body=(html_body)
      if html_body.nil?
        fail ArgumentError, 'html_body cannot be nil'
      end

      if html_body.to_s.length > 26214400
        fail ArgumentError, 'invalid value for "html_body", the character length must be smaller than or equal to 26214400.'
      end

      if html_body.to_s.length < 1
        fail ArgumentError, 'invalid value for "html_body", the character length must be greater than or equal to 1.'
      end

      @html_body = html_body
    end

    # Custom attribute writer method with validation
    # @param [Object] return_path Value to be assigned
    def return_path=(return_path)
      if return_path.nil?
        fail ArgumentError, 'return_path cannot be nil'
      end

      if return_path.to_s.length > 254
        fail ArgumentError, 'invalid value for "return_path", the character length must be smaller than or equal to 254.'
      end

      @return_path = return_path
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      if subject.to_s.length > 998
        fail ArgumentError, 'invalid value for "subject", the character length must be smaller than or equal to 998.'
      end

      if subject.to_s.length < 1
        fail ArgumentError, 'invalid value for "subject", the character length must be greater than or equal to 1.'
      end

      pattern = Regexp.new(/^[^\r\n]*$/)
      if subject !~ pattern
        fail ArgumentError, "invalid value for \"subject\", must conform to the pattern #{pattern}."
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] text_body Value to be assigned
    def text_body=(text_body)
      if text_body.nil?
        fail ArgumentError, 'text_body cannot be nil'
      end

      if text_body.to_s.length > 26214400
        fail ArgumentError, 'invalid value for "text_body", the character length must be smaller than or equal to 26214400.'
      end

      @text_body = text_body
    end

    # Custom attribute writer method with validation
    # @param [Object] to Value to be assigned
    def to=(to)
      if to.nil?
        fail ArgumentError, 'to cannot be nil'
      end

      @to = to
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          attachments == o.attachments &&
          bcc == o.bcc &&
          cc == o.cc &&
          custom_headers == o.custom_headers &&
          from == o.from &&
          html_body == o.html_body &&
          reply_to == o.reply_to &&
          return_path == o.return_path &&
          subject == o.subject &&
          text_body == o.text_body &&
          to == o.to
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attachments, bcc, cc, custom_headers, from, html_body, reply_to, return_path, subject, text_body, to].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
