<?php

/**
 * MailboxDomain
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Management\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Management\ObjectSerializer;

/**
 * MailboxDomain Class Doc Comment
 *
 * @package  Sendmux\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MailboxDomain implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MailboxDomain';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'created_at' => 'string',
        'dns_records' => '\Sendmux\Management\Model\MailboxDomainDnsRecords',
        'domain' => 'string',
        'id' => 'string',
        'mailbox_count' => 'int',
        'mode' => 'string',
        'ses_dkim_status' => 'string',
        'verification_status' => 'string',
        'verified_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'created_at' => null,
        'dns_records' => null,
        'domain' => null,
        'id' => null,
        'mailbox_count' => null,
        'mode' => null,
        'ses_dkim_status' => null,
        'verification_status' => null,
        'verified_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'created_at' => false,
        'dns_records' => false,
        'domain' => false,
        'id' => false,
        'mailbox_count' => false,
        'mode' => false,
        'ses_dkim_status' => true,
        'verification_status' => false,
        'verified_at' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'created_at' => 'created_at',
        'dns_records' => 'dns_records',
        'domain' => 'domain',
        'id' => 'id',
        'mailbox_count' => 'mailbox_count',
        'mode' => 'mode',
        'ses_dkim_status' => 'ses_dkim_status',
        'verification_status' => 'verification_status',
        'verified_at' => 'verified_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'created_at' => 'setCreatedAt',
        'dns_records' => 'setDnsRecords',
        'domain' => 'setDomain',
        'id' => 'setId',
        'mailbox_count' => 'setMailboxCount',
        'mode' => 'setMode',
        'ses_dkim_status' => 'setSesDkimStatus',
        'verification_status' => 'setVerificationStatus',
        'verified_at' => 'setVerifiedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'created_at' => 'getCreatedAt',
        'dns_records' => 'getDnsRecords',
        'domain' => 'getDomain',
        'id' => 'getId',
        'mailbox_count' => 'getMailboxCount',
        'mode' => 'getMode',
        'ses_dkim_status' => 'getSesDkimStatus',
        'verification_status' => 'getVerificationStatus',
        'verified_at' => 'getVerifiedAt'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const MODE_SEND_ONLY = 'send_only';
    public const MODE_SEND_RECEIVE = 'send_receive';
    public const MODE_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
    public const VERIFICATION_STATUS_PENDING = 'pending';
    public const VERIFICATION_STATUS_VERIFIED = 'verified';
    public const VERIFICATION_STATUS_FAILED = 'failed';
    public const VERIFICATION_STATUS_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getModeAllowableValues()
    {
        return [
            self::MODE_SEND_ONLY,
            self::MODE_SEND_RECEIVE,
            self::MODE_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getVerificationStatusAllowableValues()
    {
        return [
            self::VERIFICATION_STATUS_PENDING,
            self::VERIFICATION_STATUS_VERIFIED,
            self::VERIFICATION_STATUS_FAILED,
            self::VERIFICATION_STATUS_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('dns_records', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('mailbox_count', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('ses_dkim_status', $data ?? [], null);
        $this->setIfExists('verification_status', $data ?? [], null);
        $this->setIfExists('verified_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['dns_records'] === null) {
            $invalidProperties[] = "'dns_records' can't be null";
        }
        if ($this->container['domain'] === null) {
            $invalidProperties[] = "'domain' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['mailbox_count'] === null) {
            $invalidProperties[] = "'mailbox_count' can't be null";
        }
        if (($this->container['mailbox_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'mailbox_count', must be bigger than or equal to 0.";
        }

        if ($this->container['mode'] === null) {
            $invalidProperties[] = "'mode' can't be null";
        }
        $allowedValues = self::getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['ses_dkim_status'] === null && !$this->isNullableSetToNull('ses_dkim_status')) {
            $invalidProperties[] = "'ses_dkim_status' is required";
        }
        if ($this->container['verification_status'] === null) {
            $invalidProperties[] = "'verification_status' can't be null";
        }
        $allowedValues = self::getVerificationStatusAllowableValues();
        if (!is_null($this->container['verification_status']) && !in_array($this->container['verification_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'verification_status', must be one of '%s'",
                $this->container['verification_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['verified_at'] === null && !$this->isNullableSetToNull('verified_at')) {
            $invalidProperties[] = "'verified_at' is required";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt(): string
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at ISO 8601 creation timestamp
     *
     * @return $this
     */
    public function setCreatedAt(string $created_at): static
    {
        if (is_null($created_at)) {
            throw new InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets dns_records
     *
     * @return \Sendmux\Management\Model\MailboxDomainDnsRecords
     */
    public function getDnsRecords(): \Sendmux\Management\Model\MailboxDomainDnsRecords
    {
        return $this->container['dns_records'];
    }

    /**
     * Sets dns_records
     *
     * @param \Sendmux\Management\Model\MailboxDomainDnsRecords $dns_records dns_records
     *
     * @return $this
     */
    public function setDnsRecords(\Sendmux\Management\Model\MailboxDomainDnsRecords $dns_records): static
    {
        if (is_null($dns_records)) {
            throw new InvalidArgumentException('non-nullable dns_records cannot be null');
        }
        $this->container['dns_records'] = $dns_records;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain(): string
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain Fully qualified domain name
     *
     * @return $this
     */
    public function setDomain(string $domain): static
    {
        if (is_null($domain)) {
            throw new InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId(): string
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Public ID
     *
     * @return $this
     */
    public function setId(string $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets mailbox_count
     *
     * @return int
     */
    public function getMailboxCount(): int
    {
        return $this->container['mailbox_count'];
    }

    /**
     * Sets mailbox_count
     *
     * @param int $mailbox_count Active mailboxes currently using this domain
     *
     * @return $this
     */
    public function setMailboxCount(int $mailbox_count): static
    {
        if (is_null($mailbox_count)) {
            throw new InvalidArgumentException('non-nullable mailbox_count cannot be null');
        }

        if (($mailbox_count < 0)) {
            throw new InvalidArgumentException('invalid value for $mailbox_count when calling MailboxDomain., must be bigger than or equal to 0.');
        }

        $this->container['mailbox_count'] = $mailbox_count;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string
     */
    public function getMode(): string
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string $mode `send_only` verifies outbound DNS only. `send_receive` also verifies MX records and can host mailboxes.
     *
     * @return $this
     */
    public function setMode(string $mode): static
    {
        if (is_null($mode)) {
            throw new InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = self::getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            $mode = self::MODE_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets ses_dkim_status
     *
     * @return string|null
     */
    public function getSesDkimStatus(): ?string
    {
        return $this->container['ses_dkim_status'];
    }

    /**
     * Sets ses_dkim_status
     *
     * @param string|null $ses_dkim_status Amazon SES DKIM status (pending/success/failed/temporary_failure/not_started)
     *
     * @return $this
     */
    public function setSesDkimStatus(?string $ses_dkim_status): static
    {
        if (is_null($ses_dkim_status)) {
            array_push($this->openAPINullablesSetToNull, 'ses_dkim_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ses_dkim_status', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ses_dkim_status'] = $ses_dkim_status;

        return $this;
    }

    /**
     * Gets verification_status
     *
     * @return string
     */
    public function getVerificationStatus(): string
    {
        return $this->container['verification_status'];
    }

    /**
     * Sets verification_status
     *
     * @param string $verification_status Current verification state
     *
     * @return $this
     */
    public function setVerificationStatus(string $verification_status): static
    {
        if (is_null($verification_status)) {
            throw new InvalidArgumentException('non-nullable verification_status cannot be null');
        }
        $allowedValues = self::getVerificationStatusAllowableValues();
        if (!in_array($verification_status, $allowedValues, true)) {
            $verification_status = self::VERIFICATION_STATUS_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['verification_status'] = $verification_status;

        return $this;
    }

    /**
     * Gets verified_at
     *
     * @return string|null
     */
    public function getVerifiedAt(): ?string
    {
        return $this->container['verified_at'];
    }

    /**
     * Sets verified_at
     *
     * @param string|null $verified_at ISO 8601 timestamp of last successful verification
     *
     * @return $this
     */
    public function setVerifiedAt(?string $verified_at): static
    {
        if (is_null($verified_at)) {
            array_push($this->openAPINullablesSetToNull, 'verified_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verified_at', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['verified_at'] = $verified_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
