<?php

/**
 * MailboxSendPolicy
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Management\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Management\ObjectSerializer;

/**
 * MailboxSendPolicy Class Doc Comment
 *
 * @package  Sendmux\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MailboxSendPolicy implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MailboxSendPolicy';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'allowed_from' => '\Sendmux\Management\Model\MailboxSendPolicyAllowedFrom',
        'allowed_reply_to' => '\Sendmux\Management\Model\MailboxSendPolicyAllowedReplyTo',
        'alternate_from' => 'string[]',
        'recipients' => '\Sendmux\Management\Model\MailboxSendPolicyRecipients'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'allowed_from' => null,
        'allowed_reply_to' => null,
        'alternate_from' => 'email',
        'recipients' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'allowed_from' => false,
        'allowed_reply_to' => false,
        'alternate_from' => false,
        'recipients' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'allowed_from' => 'allowed_from',
        'allowed_reply_to' => 'allowed_reply_to',
        'alternate_from' => 'alternate_from',
        'recipients' => 'recipients'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'allowed_from' => 'setAllowedFrom',
        'allowed_reply_to' => 'setAllowedReplyTo',
        'alternate_from' => 'setAlternateFrom',
        'recipients' => 'setRecipients'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'allowed_from' => 'getAllowedFrom',
        'allowed_reply_to' => 'getAllowedReplyTo',
        'alternate_from' => 'getAlternateFrom',
        'recipients' => 'getRecipients'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('allowed_from', $data ?? [], null);
        $this->setIfExists('allowed_reply_to', $data ?? [], null);
        $this->setIfExists('alternate_from', $data ?? [], []);
        $this->setIfExists('recipients', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['alternate_from']) && (count($this->container['alternate_from']) > 100)) {
            $invalidProperties[] = "invalid value for 'alternate_from', number of items must be less than or equal to 100.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allowed_from
     *
     * @return \Sendmux\Management\Model\MailboxSendPolicyAllowedFrom|null
     */
    public function getAllowedFrom(): ?\Sendmux\Management\Model\MailboxSendPolicyAllowedFrom
    {
        return $this->container['allowed_from'];
    }

    /**
     * Sets allowed_from
     *
     * @param \Sendmux\Management\Model\MailboxSendPolicyAllowedFrom|null $allowed_from allowed_from
     *
     * @return $this
     */
    public function setAllowedFrom(?\Sendmux\Management\Model\MailboxSendPolicyAllowedFrom $allowed_from): static
    {
        if (is_null($allowed_from)) {
            throw new InvalidArgumentException('non-nullable allowed_from cannot be null');
        }
        $this->container['allowed_from'] = $allowed_from;

        return $this;
    }

    /**
     * Gets allowed_reply_to
     *
     * @return \Sendmux\Management\Model\MailboxSendPolicyAllowedReplyTo|null
     */
    public function getAllowedReplyTo(): ?\Sendmux\Management\Model\MailboxSendPolicyAllowedReplyTo
    {
        return $this->container['allowed_reply_to'];
    }

    /**
     * Sets allowed_reply_to
     *
     * @param \Sendmux\Management\Model\MailboxSendPolicyAllowedReplyTo|null $allowed_reply_to allowed_reply_to
     *
     * @return $this
     */
    public function setAllowedReplyTo(?\Sendmux\Management\Model\MailboxSendPolicyAllowedReplyTo $allowed_reply_to): static
    {
        if (is_null($allowed_reply_to)) {
            throw new InvalidArgumentException('non-nullable allowed_reply_to cannot be null');
        }
        $this->container['allowed_reply_to'] = $allowed_reply_to;

        return $this;
    }

    /**
     * Gets alternate_from
     *
     * @return string[]|null
     */
    public function getAlternateFrom(): ?array
    {
        return $this->container['alternate_from'];
    }

    /**
     * Sets alternate_from
     *
     * @param string[]|null $alternate_from Ordered fallback From addresses; every policy level must explicitly allow each alternative.
     *
     * @return $this
     */
    public function setAlternateFrom(?array $alternate_from): static
    {
        if (is_null($alternate_from)) {
            throw new InvalidArgumentException('non-nullable alternate_from cannot be null');
        }

        if ((count($alternate_from) > 100)) {
            throw new InvalidArgumentException('invalid value for $alternate_from when calling MailboxSendPolicy., number of items must be less than or equal to 100.');
        }
        $this->container['alternate_from'] = $alternate_from;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \Sendmux\Management\Model\MailboxSendPolicyRecipients|null
     */
    public function getRecipients(): ?\Sendmux\Management\Model\MailboxSendPolicyRecipients
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \Sendmux\Management\Model\MailboxSendPolicyRecipients|null $recipients recipients
     *
     * @return $this
     */
    public function setRecipients(?\Sendmux\Management\Model\MailboxSendPolicyRecipients $recipients): static
    {
        if (is_null($recipients)) {
            throw new InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
