<?php

/**
 * ProviderTypeCounts
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Management\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Management\ObjectSerializer;

/**
 * ProviderTypeCounts Class Doc Comment
 *
 * @package  Sendmux\Management
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ProviderTypeCounts implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ProviderTypeCounts';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'amazon_ses' => 'float',
        'gmail_api' => 'float',
        'outlook_api' => 'float',
        'smtp' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'amazon_ses' => null,
        'gmail_api' => null,
        'outlook_api' => null,
        'smtp' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'amazon_ses' => false,
        'gmail_api' => false,
        'outlook_api' => false,
        'smtp' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'amazon_ses' => 'amazon_ses',
        'gmail_api' => 'gmail_api',
        'outlook_api' => 'outlook_api',
        'smtp' => 'smtp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'amazon_ses' => 'setAmazonSes',
        'gmail_api' => 'setGmailApi',
        'outlook_api' => 'setOutlookApi',
        'smtp' => 'setSmtp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'amazon_ses' => 'getAmazonSes',
        'gmail_api' => 'getGmailApi',
        'outlook_api' => 'getOutlookApi',
        'smtp' => 'getSmtp'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amazon_ses', $data ?? [], null);
        $this->setIfExists('gmail_api', $data ?? [], null);
        $this->setIfExists('outlook_api', $data ?? [], null);
        $this->setIfExists('smtp', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['amazon_ses'] === null) {
            $invalidProperties[] = "'amazon_ses' can't be null";
        }
        if ($this->container['gmail_api'] === null) {
            $invalidProperties[] = "'gmail_api' can't be null";
        }
        if ($this->container['outlook_api'] === null) {
            $invalidProperties[] = "'outlook_api' can't be null";
        }
        if ($this->container['smtp'] === null) {
            $invalidProperties[] = "'smtp' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amazon_ses
     *
     * @return float
     */
    public function getAmazonSes(): float
    {
        return $this->container['amazon_ses'];
    }

    /**
     * Sets amazon_ses
     *
     * @param float $amazon_ses Number of shared Amazon SES accounts
     *
     * @return $this
     */
    public function setAmazonSes(float $amazon_ses): static
    {
        if (is_null($amazon_ses)) {
            throw new InvalidArgumentException('non-nullable amazon_ses cannot be null');
        }
        $this->container['amazon_ses'] = $amazon_ses;

        return $this;
    }

    /**
     * Gets gmail_api
     *
     * @return float
     */
    public function getGmailApi(): float
    {
        return $this->container['gmail_api'];
    }

    /**
     * Sets gmail_api
     *
     * @param float $gmail_api Number of Gmail API accounts
     *
     * @return $this
     */
    public function setGmailApi(float $gmail_api): static
    {
        if (is_null($gmail_api)) {
            throw new InvalidArgumentException('non-nullable gmail_api cannot be null');
        }
        $this->container['gmail_api'] = $gmail_api;

        return $this;
    }

    /**
     * Gets outlook_api
     *
     * @return float
     */
    public function getOutlookApi(): float
    {
        return $this->container['outlook_api'];
    }

    /**
     * Sets outlook_api
     *
     * @param float $outlook_api Number of Outlook API accounts
     *
     * @return $this
     */
    public function setOutlookApi(float $outlook_api): static
    {
        if (is_null($outlook_api)) {
            throw new InvalidArgumentException('non-nullable outlook_api cannot be null');
        }
        $this->container['outlook_api'] = $outlook_api;

        return $this;
    }

    /**
     * Gets smtp
     *
     * @return float
     */
    public function getSmtp(): float
    {
        return $this->container['smtp'];
    }

    /**
     * Sets smtp
     *
     * @param float $smtp Number of SMTP accounts
     *
     * @return $this
     */
    public function setSmtp(float $smtp): static
    {
        if (is_null($smtp)) {
            throw new InvalidArgumentException('non-nullable smtp cannot be null');
        }
        $this->container['smtp'] = $smtp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
