<?php

/**
 * MailboxTypedChangesTypes
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Mailbox\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Mailbox\ObjectSerializer;

/**
 * MailboxTypedChangesTypes Class Doc Comment
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MailboxTypedChangesTypes implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MailboxTypedChanges_types';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'folders' => '\Sendmux\Mailbox\Model\MailboxChanges',
        'identities' => '\Sendmux\Mailbox\Model\MailboxChanges',
        'messages' => '\Sendmux\Mailbox\Model\MailboxChanges',
        'quotas' => '\Sendmux\Mailbox\Model\MailboxChanges',
        'submissions' => '\Sendmux\Mailbox\Model\MailboxChanges',
        'threads' => '\Sendmux\Mailbox\Model\MailboxChanges'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'folders' => null,
        'identities' => null,
        'messages' => null,
        'quotas' => null,
        'submissions' => null,
        'threads' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'folders' => false,
        'identities' => false,
        'messages' => false,
        'quotas' => false,
        'submissions' => false,
        'threads' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'folders' => 'folders',
        'identities' => 'identities',
        'messages' => 'messages',
        'quotas' => 'quotas',
        'submissions' => 'submissions',
        'threads' => 'threads'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'folders' => 'setFolders',
        'identities' => 'setIdentities',
        'messages' => 'setMessages',
        'quotas' => 'setQuotas',
        'submissions' => 'setSubmissions',
        'threads' => 'setThreads'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'folders' => 'getFolders',
        'identities' => 'getIdentities',
        'messages' => 'getMessages',
        'quotas' => 'getQuotas',
        'submissions' => 'getSubmissions',
        'threads' => 'getThreads'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('folders', $data ?? [], null);
        $this->setIfExists('identities', $data ?? [], null);
        $this->setIfExists('messages', $data ?? [], null);
        $this->setIfExists('quotas', $data ?? [], null);
        $this->setIfExists('submissions', $data ?? [], null);
        $this->setIfExists('threads', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets folders
     *
     * @return \Sendmux\Mailbox\Model\MailboxChanges|null
     */
    public function getFolders(): ?\Sendmux\Mailbox\Model\MailboxChanges
    {
        return $this->container['folders'];
    }

    /**
     * Sets folders
     *
     * @param \Sendmux\Mailbox\Model\MailboxChanges|null $folders folders
     *
     * @return $this
     */
    public function setFolders(?\Sendmux\Mailbox\Model\MailboxChanges $folders): static
    {
        if (is_null($folders)) {
            throw new InvalidArgumentException('non-nullable folders cannot be null');
        }
        $this->container['folders'] = $folders;

        return $this;
    }

    /**
     * Gets identities
     *
     * @return \Sendmux\Mailbox\Model\MailboxChanges|null
     */
    public function getIdentities(): ?\Sendmux\Mailbox\Model\MailboxChanges
    {
        return $this->container['identities'];
    }

    /**
     * Sets identities
     *
     * @param \Sendmux\Mailbox\Model\MailboxChanges|null $identities identities
     *
     * @return $this
     */
    public function setIdentities(?\Sendmux\Mailbox\Model\MailboxChanges $identities): static
    {
        if (is_null($identities)) {
            throw new InvalidArgumentException('non-nullable identities cannot be null');
        }
        $this->container['identities'] = $identities;

        return $this;
    }

    /**
     * Gets messages
     *
     * @return \Sendmux\Mailbox\Model\MailboxChanges|null
     */
    public function getMessages(): ?\Sendmux\Mailbox\Model\MailboxChanges
    {
        return $this->container['messages'];
    }

    /**
     * Sets messages
     *
     * @param \Sendmux\Mailbox\Model\MailboxChanges|null $messages messages
     *
     * @return $this
     */
    public function setMessages(?\Sendmux\Mailbox\Model\MailboxChanges $messages): static
    {
        if (is_null($messages)) {
            throw new InvalidArgumentException('non-nullable messages cannot be null');
        }
        $this->container['messages'] = $messages;

        return $this;
    }

    /**
     * Gets quotas
     *
     * @return \Sendmux\Mailbox\Model\MailboxChanges|null
     */
    public function getQuotas(): ?\Sendmux\Mailbox\Model\MailboxChanges
    {
        return $this->container['quotas'];
    }

    /**
     * Sets quotas
     *
     * @param \Sendmux\Mailbox\Model\MailboxChanges|null $quotas quotas
     *
     * @return $this
     */
    public function setQuotas(?\Sendmux\Mailbox\Model\MailboxChanges $quotas): static
    {
        if (is_null($quotas)) {
            throw new InvalidArgumentException('non-nullable quotas cannot be null');
        }
        $this->container['quotas'] = $quotas;

        return $this;
    }

    /**
     * Gets submissions
     *
     * @return \Sendmux\Mailbox\Model\MailboxChanges|null
     */
    public function getSubmissions(): ?\Sendmux\Mailbox\Model\MailboxChanges
    {
        return $this->container['submissions'];
    }

    /**
     * Sets submissions
     *
     * @param \Sendmux\Mailbox\Model\MailboxChanges|null $submissions submissions
     *
     * @return $this
     */
    public function setSubmissions(?\Sendmux\Mailbox\Model\MailboxChanges $submissions): static
    {
        if (is_null($submissions)) {
            throw new InvalidArgumentException('non-nullable submissions cannot be null');
        }
        $this->container['submissions'] = $submissions;

        return $this;
    }

    /**
     * Gets threads
     *
     * @return \Sendmux\Mailbox\Model\MailboxChanges|null
     */
    public function getThreads(): ?\Sendmux\Mailbox\Model\MailboxChanges
    {
        return $this->container['threads'];
    }

    /**
     * Sets threads
     *
     * @param \Sendmux\Mailbox\Model\MailboxChanges|null $threads threads
     *
     * @return $this
     */
    public function setThreads(?\Sendmux\Mailbox\Model\MailboxChanges $threads): static
    {
        if (is_null($threads)) {
            throw new InvalidArgumentException('non-nullable threads cannot be null');
        }
        $this->container['threads'] = $threads;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
