<?php

/**
 * MailboxRealtimeEvent
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Mailbox\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Mailbox\ObjectSerializer;

/**
 * MailboxRealtimeEvent Class Doc Comment
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MailboxRealtimeEvent implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MailboxRealtimeEvent';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'event_type' => 'string',
        'is_spam' => 'bool',
        'mailbox_id' => 'string',
        'message' => '\Sendmux\Mailbox\Model\MailboxRealtimeMessage',
        'message_id' => 'string',
        'message_id_kind' => 'string',
        'occurred_at' => 'string',
        'recipients' => 'string[]',
        'sender' => 'string',
        'team_public_id' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'event_type' => null,
        'is_spam' => null,
        'mailbox_id' => null,
        'message' => null,
        'message_id' => null,
        'message_id_kind' => null,
        'occurred_at' => null,
        'recipients' => null,
        'sender' => null,
        'team_public_id' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'event_type' => false,
        'is_spam' => true,
        'mailbox_id' => false,
        'message' => false,
        'message_id' => true,
        'message_id_kind' => true,
        'occurred_at' => false,
        'recipients' => false,
        'sender' => true,
        'team_public_id' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'event_type' => 'event_type',
        'is_spam' => 'is_spam',
        'mailbox_id' => 'mailbox_id',
        'message' => 'message',
        'message_id' => 'message_id',
        'message_id_kind' => 'message_id_kind',
        'occurred_at' => 'occurred_at',
        'recipients' => 'recipients',
        'sender' => 'sender',
        'team_public_id' => 'team_public_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'event_type' => 'setEventType',
        'is_spam' => 'setIsSpam',
        'mailbox_id' => 'setMailboxId',
        'message' => 'setMessage',
        'message_id' => 'setMessageId',
        'message_id_kind' => 'setMessageIdKind',
        'occurred_at' => 'setOccurredAt',
        'recipients' => 'setRecipients',
        'sender' => 'setSender',
        'team_public_id' => 'setTeamPublicId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'event_type' => 'getEventType',
        'is_spam' => 'getIsSpam',
        'mailbox_id' => 'getMailboxId',
        'message' => 'getMessage',
        'message_id' => 'getMessageId',
        'message_id_kind' => 'getMessageIdKind',
        'occurred_at' => 'getOccurredAt',
        'recipients' => 'getRecipients',
        'sender' => 'getSender',
        'team_public_id' => 'getTeamPublicId'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const EVENT_TYPE_MESSAGE_RECEIVED = 'message.received';
    public const EVENT_TYPE_MESSAGE_RECEIVED_SPAM = 'message.received.spam';
    public const EVENT_TYPE_SYNC_REQUIRED = 'sync_required';
    public const EVENT_TYPE_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
    public const MESSAGE_ID_KIND_PROVIDER = 'provider';
    public const MESSAGE_ID_KIND_RFC5322 = 'rfc5322';
    public const MESSAGE_ID_KIND_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getEventTypeAllowableValues()
    {
        return [
            self::EVENT_TYPE_MESSAGE_RECEIVED,
            self::EVENT_TYPE_MESSAGE_RECEIVED_SPAM,
            self::EVENT_TYPE_SYNC_REQUIRED,
            self::EVENT_TYPE_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getMessageIdKindAllowableValues()
    {
        return [
            self::MESSAGE_ID_KIND_PROVIDER,
            self::MESSAGE_ID_KIND_RFC5322,
            self::MESSAGE_ID_KIND_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('event_type', $data ?? [], null);
        $this->setIfExists('is_spam', $data ?? [], null);
        $this->setIfExists('mailbox_id', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('message_id', $data ?? [], null);
        $this->setIfExists('message_id_kind', $data ?? [], null);
        $this->setIfExists('occurred_at', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('sender', $data ?? [], null);
        $this->setIfExists('team_public_id', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['event_type'] === null) {
            $invalidProperties[] = "'event_type' can't be null";
        }
        $allowedValues = self::getEventTypeAllowableValues();
        if (!is_null($this->container['event_type']) && !in_array($this->container['event_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'event_type', must be one of '%s'",
                $this->container['event_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['is_spam'] === null && !$this->isNullableSetToNull('is_spam')) {
            $invalidProperties[] = "'is_spam' is required";
        }
        if ($this->container['mailbox_id'] === null) {
            $invalidProperties[] = "'mailbox_id' can't be null";
        }
        if ($this->container['message'] === null) {
            $invalidProperties[] = "'message' can't be null";
        }
        if ($this->container['message_id'] === null && !$this->isNullableSetToNull('message_id')) {
            $invalidProperties[] = "'message_id' is required";
        }
        if ($this->container['message_id_kind'] === null && !$this->isNullableSetToNull('message_id_kind')) {
            $invalidProperties[] = "'message_id_kind' is required";
        }
        $allowedValues = self::getMessageIdKindAllowableValues();
        if (!is_null($this->container['message_id_kind']) && !in_array($this->container['message_id_kind'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'message_id_kind', must be one of '%s'",
                $this->container['message_id_kind'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['occurred_at'] === null) {
            $invalidProperties[] = "'occurred_at' can't be null";
        }
        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        if ($this->container['sender'] === null && !$this->isNullableSetToNull('sender')) {
            $invalidProperties[] = "'sender' is required";
        }
        if ($this->container['team_public_id'] === null) {
            $invalidProperties[] = "'team_public_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets event_type
     *
     * @return string
     */
    public function getEventType(): string
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string $event_type event_type
     *
     * @return $this
     */
    public function setEventType(string $event_type): static
    {
        if (is_null($event_type)) {
            throw new InvalidArgumentException('non-nullable event_type cannot be null');
        }
        $allowedValues = self::getEventTypeAllowableValues();
        if (!in_array($event_type, $allowedValues, true)) {
            $event_type = self::EVENT_TYPE_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets is_spam
     *
     * @return bool|null
     */
    public function getIsSpam(): ?bool
    {
        return $this->container['is_spam'];
    }

    /**
     * Sets is_spam
     *
     * @param bool|null $is_spam is_spam
     *
     * @return $this
     */
    public function setIsSpam(?bool $is_spam): static
    {
        if (is_null($is_spam)) {
            array_push($this->openAPINullablesSetToNull, 'is_spam');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_spam', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_spam'] = $is_spam;

        return $this;
    }

    /**
     * Gets mailbox_id
     *
     * @return string
     */
    public function getMailboxId(): string
    {
        return $this->container['mailbox_id'];
    }

    /**
     * Sets mailbox_id
     *
     * @param string $mailbox_id mailbox_id
     *
     * @return $this
     */
    public function setMailboxId(string $mailbox_id): static
    {
        if (is_null($mailbox_id)) {
            throw new InvalidArgumentException('non-nullable mailbox_id cannot be null');
        }
        $this->container['mailbox_id'] = $mailbox_id;

        return $this;
    }

    /**
     * Gets message
     *
     * @return \Sendmux\Mailbox\Model\MailboxRealtimeMessage
     */
    public function getMessage(): \Sendmux\Mailbox\Model\MailboxRealtimeMessage
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param \Sendmux\Mailbox\Model\MailboxRealtimeMessage $message message
     *
     * @return $this
     */
    public function setMessage(\Sendmux\Mailbox\Model\MailboxRealtimeMessage $message): static
    {
        if (is_null($message)) {
            throw new InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets message_id
     *
     * @return string|null
     */
    public function getMessageId(): ?string
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param string|null $message_id message_id
     *
     * @return $this
     */
    public function setMessageId(?string $message_id): static
    {
        if (is_null($message_id)) {
            array_push($this->openAPINullablesSetToNull, 'message_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('message_id', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets message_id_kind
     *
     * @return string|null
     */
    public function getMessageIdKind(): ?string
    {
        return $this->container['message_id_kind'];
    }

    /**
     * Sets message_id_kind
     *
     * @param string|null $message_id_kind message_id_kind
     *
     * @return $this
     */
    public function setMessageIdKind(?string $message_id_kind): static
    {
        if (is_null($message_id_kind)) {
            array_push($this->openAPINullablesSetToNull, 'message_id_kind');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('message_id_kind', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = self::getMessageIdKindAllowableValues();
        if (!is_null($message_id_kind) && !in_array($message_id_kind, $allowedValues, true)) {
            $message_id_kind = self::MESSAGE_ID_KIND_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['message_id_kind'] = $message_id_kind;

        return $this;
    }

    /**
     * Gets occurred_at
     *
     * @return string
     */
    public function getOccurredAt(): string
    {
        return $this->container['occurred_at'];
    }

    /**
     * Sets occurred_at
     *
     * @param string $occurred_at occurred_at
     *
     * @return $this
     */
    public function setOccurredAt(string $occurred_at): static
    {
        if (is_null($occurred_at)) {
            throw new InvalidArgumentException('non-nullable occurred_at cannot be null');
        }
        $this->container['occurred_at'] = $occurred_at;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return string[]
     */
    public function getRecipients(): array
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param string[] $recipients recipients
     *
     * @return $this
     */
    public function setRecipients(array $recipients): static
    {
        if (is_null($recipients)) {
            throw new InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return string|null
     */
    public function getSender(): ?string
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param string|null $sender sender
     *
     * @return $this
     */
    public function setSender(?string $sender): static
    {
        if (is_null($sender)) {
            array_push($this->openAPINullablesSetToNull, 'sender');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sender', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets team_public_id
     *
     * @return string
     */
    public function getTeamPublicId(): string
    {
        return $this->container['team_public_id'];
    }

    /**
     * Sets team_public_id
     *
     * @param string $team_public_id team_public_id
     *
     * @return $this
     */
    public function setTeamPublicId(string $team_public_id): static
    {
        if (is_null($team_public_id)) {
            throw new InvalidArgumentException('non-nullable team_public_id cannot be null');
        }
        $this->container['team_public_id'] = $team_public_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
