<?php

/**
 * MailboxSessionCapabilitiesMessages
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Mailbox\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Mailbox\ObjectSerializer;

/**
 * MailboxSessionCapabilitiesMessages Class Doc Comment
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MailboxSessionCapabilitiesMessages implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MailboxSession_capabilities_messages';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'batch_get' => 'bool',
        'batch_update' => 'bool',
        'changes' => 'bool',
        'clean_content' => 'bool',
        'count' => 'bool',
        'delete' => 'bool',
        'detail' => 'bool',
        'keywords' => 'bool',
        'list' => 'bool',
        'permanent_delete' => 'bool',
        'query_changes' => 'bool',
        'raw_body' => 'bool',
        'search_snippets' => 'bool',
        'update_fields' => 'string[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'batch_get' => null,
        'batch_update' => null,
        'changes' => null,
        'clean_content' => null,
        'count' => null,
        'delete' => null,
        'detail' => null,
        'keywords' => null,
        'list' => null,
        'permanent_delete' => null,
        'query_changes' => null,
        'raw_body' => null,
        'search_snippets' => null,
        'update_fields' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'batch_get' => false,
        'batch_update' => false,
        'changes' => false,
        'clean_content' => false,
        'count' => false,
        'delete' => false,
        'detail' => false,
        'keywords' => false,
        'list' => false,
        'permanent_delete' => false,
        'query_changes' => false,
        'raw_body' => false,
        'search_snippets' => false,
        'update_fields' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'batch_get' => 'batch_get',
        'batch_update' => 'batch_update',
        'changes' => 'changes',
        'clean_content' => 'clean_content',
        'count' => 'count',
        'delete' => 'delete',
        'detail' => 'detail',
        'keywords' => 'keywords',
        'list' => 'list',
        'permanent_delete' => 'permanent_delete',
        'query_changes' => 'query_changes',
        'raw_body' => 'raw_body',
        'search_snippets' => 'search_snippets',
        'update_fields' => 'update_fields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'batch_get' => 'setBatchGet',
        'batch_update' => 'setBatchUpdate',
        'changes' => 'setChanges',
        'clean_content' => 'setCleanContent',
        'count' => 'setCount',
        'delete' => 'setDelete',
        'detail' => 'setDetail',
        'keywords' => 'setKeywords',
        'list' => 'setList',
        'permanent_delete' => 'setPermanentDelete',
        'query_changes' => 'setQueryChanges',
        'raw_body' => 'setRawBody',
        'search_snippets' => 'setSearchSnippets',
        'update_fields' => 'setUpdateFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'batch_get' => 'getBatchGet',
        'batch_update' => 'getBatchUpdate',
        'changes' => 'getChanges',
        'clean_content' => 'getCleanContent',
        'count' => 'getCount',
        'delete' => 'getDelete',
        'detail' => 'getDetail',
        'keywords' => 'getKeywords',
        'list' => 'getList',
        'permanent_delete' => 'getPermanentDelete',
        'query_changes' => 'getQueryChanges',
        'raw_body' => 'getRawBody',
        'search_snippets' => 'getSearchSnippets',
        'update_fields' => 'getUpdateFields'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const UPDATE_FIELDS_SEEN = 'seen';
    public const UPDATE_FIELDS_FLAGGED = 'flagged';
    public const UPDATE_FIELDS_KEYWORDS = 'keywords';
    public const UPDATE_FIELDS_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getUpdateFieldsAllowableValues()
    {
        return [
            self::UPDATE_FIELDS_SEEN,
            self::UPDATE_FIELDS_FLAGGED,
            self::UPDATE_FIELDS_KEYWORDS,
            self::UPDATE_FIELDS_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('batch_get', $data ?? [], null);
        $this->setIfExists('batch_update', $data ?? [], null);
        $this->setIfExists('changes', $data ?? [], null);
        $this->setIfExists('clean_content', $data ?? [], null);
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('delete', $data ?? [], null);
        $this->setIfExists('detail', $data ?? [], null);
        $this->setIfExists('keywords', $data ?? [], null);
        $this->setIfExists('list', $data ?? [], null);
        $this->setIfExists('permanent_delete', $data ?? [], null);
        $this->setIfExists('query_changes', $data ?? [], null);
        $this->setIfExists('raw_body', $data ?? [], null);
        $this->setIfExists('search_snippets', $data ?? [], null);
        $this->setIfExists('update_fields', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['batch_get'] === null) {
            $invalidProperties[] = "'batch_get' can't be null";
        }
        if ($this->container['batch_update'] === null) {
            $invalidProperties[] = "'batch_update' can't be null";
        }
        if ($this->container['changes'] === null) {
            $invalidProperties[] = "'changes' can't be null";
        }
        if ($this->container['clean_content'] === null) {
            $invalidProperties[] = "'clean_content' can't be null";
        }
        if ($this->container['count'] === null) {
            $invalidProperties[] = "'count' can't be null";
        }
        if ($this->container['delete'] === null) {
            $invalidProperties[] = "'delete' can't be null";
        }
        if ($this->container['detail'] === null) {
            $invalidProperties[] = "'detail' can't be null";
        }
        if ($this->container['keywords'] === null) {
            $invalidProperties[] = "'keywords' can't be null";
        }
        if ($this->container['list'] === null) {
            $invalidProperties[] = "'list' can't be null";
        }
        if ($this->container['permanent_delete'] === null) {
            $invalidProperties[] = "'permanent_delete' can't be null";
        }
        if ($this->container['query_changes'] === null) {
            $invalidProperties[] = "'query_changes' can't be null";
        }
        if ($this->container['raw_body'] === null) {
            $invalidProperties[] = "'raw_body' can't be null";
        }
        if ($this->container['search_snippets'] === null) {
            $invalidProperties[] = "'search_snippets' can't be null";
        }
        if ($this->container['update_fields'] === null) {
            $invalidProperties[] = "'update_fields' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets batch_get
     *
     * @return bool
     */
    public function getBatchGet(): bool
    {
        return $this->container['batch_get'];
    }

    /**
     * Sets batch_get
     *
     * @param bool $batch_get batch_get
     *
     * @return $this
     */
    public function setBatchGet(bool $batch_get): static
    {
        if (is_null($batch_get)) {
            throw new InvalidArgumentException('non-nullable batch_get cannot be null');
        }
        $this->container['batch_get'] = $batch_get;

        return $this;
    }

    /**
     * Gets batch_update
     *
     * @return bool
     */
    public function getBatchUpdate(): bool
    {
        return $this->container['batch_update'];
    }

    /**
     * Sets batch_update
     *
     * @param bool $batch_update batch_update
     *
     * @return $this
     */
    public function setBatchUpdate(bool $batch_update): static
    {
        if (is_null($batch_update)) {
            throw new InvalidArgumentException('non-nullable batch_update cannot be null');
        }
        $this->container['batch_update'] = $batch_update;

        return $this;
    }

    /**
     * Gets changes
     *
     * @return bool
     */
    public function getChanges(): bool
    {
        return $this->container['changes'];
    }

    /**
     * Sets changes
     *
     * @param bool $changes changes
     *
     * @return $this
     */
    public function setChanges(bool $changes): static
    {
        if (is_null($changes)) {
            throw new InvalidArgumentException('non-nullable changes cannot be null');
        }
        $this->container['changes'] = $changes;

        return $this;
    }

    /**
     * Gets clean_content
     *
     * @return bool
     */
    public function getCleanContent(): bool
    {
        return $this->container['clean_content'];
    }

    /**
     * Sets clean_content
     *
     * @param bool $clean_content clean_content
     *
     * @return $this
     */
    public function setCleanContent(bool $clean_content): static
    {
        if (is_null($clean_content)) {
            throw new InvalidArgumentException('non-nullable clean_content cannot be null');
        }
        $this->container['clean_content'] = $clean_content;

        return $this;
    }

    /**
     * Gets count
     *
     * @return bool
     */
    public function getCount(): bool
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param bool $count count
     *
     * @return $this
     */
    public function setCount(bool $count): static
    {
        if (is_null($count)) {
            throw new InvalidArgumentException('non-nullable count cannot be null');
        }
        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets delete
     *
     * @return bool
     */
    public function getDelete(): bool
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     *
     * @param bool $delete delete
     *
     * @return $this
     */
    public function setDelete(bool $delete): static
    {
        if (is_null($delete)) {
            throw new InvalidArgumentException('non-nullable delete cannot be null');
        }
        $this->container['delete'] = $delete;

        return $this;
    }

    /**
     * Gets detail
     *
     * @return bool
     */
    public function getDetail(): bool
    {
        return $this->container['detail'];
    }

    /**
     * Sets detail
     *
     * @param bool $detail detail
     *
     * @return $this
     */
    public function setDetail(bool $detail): static
    {
        if (is_null($detail)) {
            throw new InvalidArgumentException('non-nullable detail cannot be null');
        }
        $this->container['detail'] = $detail;

        return $this;
    }

    /**
     * Gets keywords
     *
     * @return bool
     */
    public function getKeywords(): bool
    {
        return $this->container['keywords'];
    }

    /**
     * Sets keywords
     *
     * @param bool $keywords keywords
     *
     * @return $this
     */
    public function setKeywords(bool $keywords): static
    {
        if (is_null($keywords)) {
            throw new InvalidArgumentException('non-nullable keywords cannot be null');
        }
        $this->container['keywords'] = $keywords;

        return $this;
    }

    /**
     * Gets list
     *
     * @return bool
     */
    public function getList(): bool
    {
        return $this->container['list'];
    }

    /**
     * Sets list
     *
     * @param bool $list list
     *
     * @return $this
     */
    public function setList(bool $list): static
    {
        if (is_null($list)) {
            throw new InvalidArgumentException('non-nullable list cannot be null');
        }
        $this->container['list'] = $list;

        return $this;
    }

    /**
     * Gets permanent_delete
     *
     * @return bool
     */
    public function getPermanentDelete(): bool
    {
        return $this->container['permanent_delete'];
    }

    /**
     * Sets permanent_delete
     *
     * @param bool $permanent_delete permanent_delete
     *
     * @return $this
     */
    public function setPermanentDelete(bool $permanent_delete): static
    {
        if (is_null($permanent_delete)) {
            throw new InvalidArgumentException('non-nullable permanent_delete cannot be null');
        }
        $this->container['permanent_delete'] = $permanent_delete;

        return $this;
    }

    /**
     * Gets query_changes
     *
     * @return bool
     */
    public function getQueryChanges(): bool
    {
        return $this->container['query_changes'];
    }

    /**
     * Sets query_changes
     *
     * @param bool $query_changes query_changes
     *
     * @return $this
     */
    public function setQueryChanges(bool $query_changes): static
    {
        if (is_null($query_changes)) {
            throw new InvalidArgumentException('non-nullable query_changes cannot be null');
        }
        $this->container['query_changes'] = $query_changes;

        return $this;
    }

    /**
     * Gets raw_body
     *
     * @return bool
     */
    public function getRawBody(): bool
    {
        return $this->container['raw_body'];
    }

    /**
     * Sets raw_body
     *
     * @param bool $raw_body raw_body
     *
     * @return $this
     */
    public function setRawBody(bool $raw_body): static
    {
        if (is_null($raw_body)) {
            throw new InvalidArgumentException('non-nullable raw_body cannot be null');
        }
        $this->container['raw_body'] = $raw_body;

        return $this;
    }

    /**
     * Gets search_snippets
     *
     * @return bool
     */
    public function getSearchSnippets(): bool
    {
        return $this->container['search_snippets'];
    }

    /**
     * Sets search_snippets
     *
     * @param bool $search_snippets search_snippets
     *
     * @return $this
     */
    public function setSearchSnippets(bool $search_snippets): static
    {
        if (is_null($search_snippets)) {
            throw new InvalidArgumentException('non-nullable search_snippets cannot be null');
        }
        $this->container['search_snippets'] = $search_snippets;

        return $this;
    }

    /**
     * Gets update_fields
     *
     * @return string[]
     */
    public function getUpdateFields(): array
    {
        return $this->container['update_fields'];
    }

    /**
     * Sets update_fields
     *
     * @param string[] $update_fields update_fields
     *
     * @return $this
     */
    public function setUpdateFields(array $update_fields): static
    {
        if (is_null($update_fields)) {
            throw new InvalidArgumentException('non-nullable update_fields cannot be null');
        }
        $allowedValues = self::getUpdateFieldsAllowableValues();
        if (array_diff($update_fields, $allowedValues)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value for 'update_fields', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['update_fields'] = $update_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
