<?php

/**
 * MailboxSessionGated
 *
 * PHP version 8.1
 *
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendmux API
 *
 * Programmatic access to your Sendmux email infrastructure.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sendmux\Mailbox\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Sendmux\Mailbox\ObjectSerializer;

/**
 * MailboxSessionGated Class Doc Comment
 *
 * @description Flags are true when a feature is intentionally unavailable through the mailbox API.
 * @package  Sendmux\Mailbox
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MailboxSessionGated implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MailboxSession_gated';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'attachment_parsing' => 'bool',
        'blob_copy' => 'bool',
        'blob_lookup' => 'bool',
        'events' => 'bool',
        'filter_script_writes' => 'bool',
        'identity_mutation' => 'bool',
        'message_copy' => 'bool',
        'message_import' => 'bool',
        'message_parse' => 'bool',
        'quota_mutation' => 'bool',
        'raw_protocol' => 'bool',
        'vacation_response' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'attachment_parsing' => null,
        'blob_copy' => null,
        'blob_lookup' => null,
        'events' => null,
        'filter_script_writes' => null,
        'identity_mutation' => null,
        'message_copy' => null,
        'message_import' => null,
        'message_parse' => null,
        'quota_mutation' => null,
        'raw_protocol' => null,
        'vacation_response' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'attachment_parsing' => false,
        'blob_copy' => false,
        'blob_lookup' => false,
        'events' => false,
        'filter_script_writes' => false,
        'identity_mutation' => false,
        'message_copy' => false,
        'message_import' => false,
        'message_parse' => false,
        'quota_mutation' => false,
        'raw_protocol' => false,
        'vacation_response' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'attachment_parsing' => 'attachment_parsing',
        'blob_copy' => 'blob_copy',
        'blob_lookup' => 'blob_lookup',
        'events' => 'events',
        'filter_script_writes' => 'filter_script_writes',
        'identity_mutation' => 'identity_mutation',
        'message_copy' => 'message_copy',
        'message_import' => 'message_import',
        'message_parse' => 'message_parse',
        'quota_mutation' => 'quota_mutation',
        'raw_protocol' => 'raw_protocol',
        'vacation_response' => 'vacation_response'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'attachment_parsing' => 'setAttachmentParsing',
        'blob_copy' => 'setBlobCopy',
        'blob_lookup' => 'setBlobLookup',
        'events' => 'setEvents',
        'filter_script_writes' => 'setFilterScriptWrites',
        'identity_mutation' => 'setIdentityMutation',
        'message_copy' => 'setMessageCopy',
        'message_import' => 'setMessageImport',
        'message_parse' => 'setMessageParse',
        'quota_mutation' => 'setQuotaMutation',
        'raw_protocol' => 'setRawProtocol',
        'vacation_response' => 'setVacationResponse'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'attachment_parsing' => 'getAttachmentParsing',
        'blob_copy' => 'getBlobCopy',
        'blob_lookup' => 'getBlobLookup',
        'events' => 'getEvents',
        'filter_script_writes' => 'getFilterScriptWrites',
        'identity_mutation' => 'getIdentityMutation',
        'message_copy' => 'getMessageCopy',
        'message_import' => 'getMessageImport',
        'message_parse' => 'getMessageParse',
        'quota_mutation' => 'getQuotaMutation',
        'raw_protocol' => 'getRawProtocol',
        'vacation_response' => 'getVacationResponse'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attachment_parsing', $data ?? [], null);
        $this->setIfExists('blob_copy', $data ?? [], null);
        $this->setIfExists('blob_lookup', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
        $this->setIfExists('filter_script_writes', $data ?? [], null);
        $this->setIfExists('identity_mutation', $data ?? [], null);
        $this->setIfExists('message_copy', $data ?? [], null);
        $this->setIfExists('message_import', $data ?? [], null);
        $this->setIfExists('message_parse', $data ?? [], null);
        $this->setIfExists('quota_mutation', $data ?? [], null);
        $this->setIfExists('raw_protocol', $data ?? [], null);
        $this->setIfExists('vacation_response', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['attachment_parsing'] === null) {
            $invalidProperties[] = "'attachment_parsing' can't be null";
        }
        if ($this->container['blob_copy'] === null) {
            $invalidProperties[] = "'blob_copy' can't be null";
        }
        if ($this->container['blob_lookup'] === null) {
            $invalidProperties[] = "'blob_lookup' can't be null";
        }
        if ($this->container['events'] === null) {
            $invalidProperties[] = "'events' can't be null";
        }
        if ($this->container['filter_script_writes'] === null) {
            $invalidProperties[] = "'filter_script_writes' can't be null";
        }
        if ($this->container['identity_mutation'] === null) {
            $invalidProperties[] = "'identity_mutation' can't be null";
        }
        if ($this->container['message_copy'] === null) {
            $invalidProperties[] = "'message_copy' can't be null";
        }
        if ($this->container['message_import'] === null) {
            $invalidProperties[] = "'message_import' can't be null";
        }
        if ($this->container['message_parse'] === null) {
            $invalidProperties[] = "'message_parse' can't be null";
        }
        if ($this->container['quota_mutation'] === null) {
            $invalidProperties[] = "'quota_mutation' can't be null";
        }
        if ($this->container['raw_protocol'] === null) {
            $invalidProperties[] = "'raw_protocol' can't be null";
        }
        if ($this->container['vacation_response'] === null) {
            $invalidProperties[] = "'vacation_response' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attachment_parsing
     *
     * @return bool
     */
    public function getAttachmentParsing(): bool
    {
        return $this->container['attachment_parsing'];
    }

    /**
     * Sets attachment_parsing
     *
     * @param bool $attachment_parsing attachment_parsing
     *
     * @return $this
     */
    public function setAttachmentParsing(bool $attachment_parsing): static
    {
        if (is_null($attachment_parsing)) {
            throw new InvalidArgumentException('non-nullable attachment_parsing cannot be null');
        }
        $this->container['attachment_parsing'] = $attachment_parsing;

        return $this;
    }

    /**
     * Gets blob_copy
     *
     * @return bool
     */
    public function getBlobCopy(): bool
    {
        return $this->container['blob_copy'];
    }

    /**
     * Sets blob_copy
     *
     * @param bool $blob_copy blob_copy
     *
     * @return $this
     */
    public function setBlobCopy(bool $blob_copy): static
    {
        if (is_null($blob_copy)) {
            throw new InvalidArgumentException('non-nullable blob_copy cannot be null');
        }
        $this->container['blob_copy'] = $blob_copy;

        return $this;
    }

    /**
     * Gets blob_lookup
     *
     * @return bool
     */
    public function getBlobLookup(): bool
    {
        return $this->container['blob_lookup'];
    }

    /**
     * Sets blob_lookup
     *
     * @param bool $blob_lookup blob_lookup
     *
     * @return $this
     */
    public function setBlobLookup(bool $blob_lookup): static
    {
        if (is_null($blob_lookup)) {
            throw new InvalidArgumentException('non-nullable blob_lookup cannot be null');
        }
        $this->container['blob_lookup'] = $blob_lookup;

        return $this;
    }

    /**
     * Gets events
     *
     * @return bool
     */
    public function getEvents(): bool
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param bool $events events
     *
     * @return $this
     */
    public function setEvents(bool $events): static
    {
        if (is_null($events)) {
            throw new InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets filter_script_writes
     *
     * @return bool
     */
    public function getFilterScriptWrites(): bool
    {
        return $this->container['filter_script_writes'];
    }

    /**
     * Sets filter_script_writes
     *
     * @param bool $filter_script_writes filter_script_writes
     *
     * @return $this
     */
    public function setFilterScriptWrites(bool $filter_script_writes): static
    {
        if (is_null($filter_script_writes)) {
            throw new InvalidArgumentException('non-nullable filter_script_writes cannot be null');
        }
        $this->container['filter_script_writes'] = $filter_script_writes;

        return $this;
    }

    /**
     * Gets identity_mutation
     *
     * @return bool
     */
    public function getIdentityMutation(): bool
    {
        return $this->container['identity_mutation'];
    }

    /**
     * Sets identity_mutation
     *
     * @param bool $identity_mutation identity_mutation
     *
     * @return $this
     */
    public function setIdentityMutation(bool $identity_mutation): static
    {
        if (is_null($identity_mutation)) {
            throw new InvalidArgumentException('non-nullable identity_mutation cannot be null');
        }
        $this->container['identity_mutation'] = $identity_mutation;

        return $this;
    }

    /**
     * Gets message_copy
     *
     * @return bool
     */
    public function getMessageCopy(): bool
    {
        return $this->container['message_copy'];
    }

    /**
     * Sets message_copy
     *
     * @param bool $message_copy message_copy
     *
     * @return $this
     */
    public function setMessageCopy(bool $message_copy): static
    {
        if (is_null($message_copy)) {
            throw new InvalidArgumentException('non-nullable message_copy cannot be null');
        }
        $this->container['message_copy'] = $message_copy;

        return $this;
    }

    /**
     * Gets message_import
     *
     * @return bool
     */
    public function getMessageImport(): bool
    {
        return $this->container['message_import'];
    }

    /**
     * Sets message_import
     *
     * @param bool $message_import message_import
     *
     * @return $this
     */
    public function setMessageImport(bool $message_import): static
    {
        if (is_null($message_import)) {
            throw new InvalidArgumentException('non-nullable message_import cannot be null');
        }
        $this->container['message_import'] = $message_import;

        return $this;
    }

    /**
     * Gets message_parse
     *
     * @return bool
     */
    public function getMessageParse(): bool
    {
        return $this->container['message_parse'];
    }

    /**
     * Sets message_parse
     *
     * @param bool $message_parse message_parse
     *
     * @return $this
     */
    public function setMessageParse(bool $message_parse): static
    {
        if (is_null($message_parse)) {
            throw new InvalidArgumentException('non-nullable message_parse cannot be null');
        }
        $this->container['message_parse'] = $message_parse;

        return $this;
    }

    /**
     * Gets quota_mutation
     *
     * @return bool
     */
    public function getQuotaMutation(): bool
    {
        return $this->container['quota_mutation'];
    }

    /**
     * Sets quota_mutation
     *
     * @param bool $quota_mutation quota_mutation
     *
     * @return $this
     */
    public function setQuotaMutation(bool $quota_mutation): static
    {
        if (is_null($quota_mutation)) {
            throw new InvalidArgumentException('non-nullable quota_mutation cannot be null');
        }
        $this->container['quota_mutation'] = $quota_mutation;

        return $this;
    }

    /**
     * Gets raw_protocol
     *
     * @return bool
     */
    public function getRawProtocol(): bool
    {
        return $this->container['raw_protocol'];
    }

    /**
     * Sets raw_protocol
     *
     * @param bool $raw_protocol raw_protocol
     *
     * @return $this
     */
    public function setRawProtocol(bool $raw_protocol): static
    {
        if (is_null($raw_protocol)) {
            throw new InvalidArgumentException('non-nullable raw_protocol cannot be null');
        }
        $this->container['raw_protocol'] = $raw_protocol;

        return $this;
    }

    /**
     * Gets vacation_response
     *
     * @return bool
     */
    public function getVacationResponse(): bool
    {
        return $this->container['vacation_response'];
    }

    /**
     * Sets vacation_response
     *
     * @param bool $vacation_response vacation_response
     *
     * @return $this
     */
    public function setVacationResponse(bool $vacation_response): static
    {
        if (is_null($vacation_response)) {
            throw new InvalidArgumentException('non-nullable vacation_response cannot be null');
        }
        $this->container['vacation_response'] = $vacation_response;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
