// This file is generated by scripts/generate-cli.mjs

import { operations } from "../../../generated/operations.js";
import { OperationCommand } from "../../../operation-command.js";

export default class SendingSendEmailBatchCommand extends OperationCommand {
  static description = operations.sendingSendEmailBatch.description;
  static operation = operations.sendingSendEmailBatch;
}
