// Code generated by scripts/generate-go.mjs. DO NOT EDIT.
package sending

import "context"

// ConnectionInvoker exposes the connection check without extending existing Invoker or Handler implementations.
// Client and server handlers may implement this optional interface.
type ConnectionInvoker interface {
	SendingGetConnection(ctx context.Context, params SendingGetConnectionParams) (SendingGetConnectionRes, error)
}

func (s *Server) invokeConnection(ctx context.Context, params SendingGetConnectionParams) (SendingGetConnectionRes, error) {
	if handler, ok := s.h.(ConnectionInvoker); ok {
		return handler.SendingGetConnection(ctx, params)
	}
	return UnimplementedHandler{}.SendingGetConnection(ctx, params)
}
