// Code generated by ogen, DO NOT EDIT.

package sending

// OperationName is the ogen operation name
type OperationName = string

const (
	SendingCompleteAttachmentUploadOperation OperationName = "SendingCompleteAttachmentUpload"
	SendingCreateAttachmentUploadOperation   OperationName = "SendingCreateAttachmentUpload"
	SendingGetAttachmentOperation            OperationName = "SendingGetAttachment"
	SendingGetOpenApiSpecOperation           OperationName = "SendingGetOpenApiSpec"
	SendingSendEmailOperation                OperationName = "SendingSendEmail"
	SendingSendEmailBatchOperation           OperationName = "SendingSendEmailBatch"
	SendingUploadAttachmentOperation         OperationName = "SendingUploadAttachment"
)
