// Code generated by ogen, DO NOT EDIT.

package sending

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// SendingCompleteAttachmentUploadParams is parameters of sendingCompleteAttachmentUpload operation.
type SendingCompleteAttachmentUploadParams struct {
	// Short-lived upload token returned by POST /emails/attachment-uploads.
	XSendmuxUploadToken string
	// Exact number of bytes in the binary request body.
	ContentLength int64
	// Upload intent ID returned by POST /emails/attachment-uploads.
	UploadID string
}

func unpackSendingCompleteAttachmentUploadParams(packed middleware.Parameters) (params SendingCompleteAttachmentUploadParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Sendmux-Upload-Token",
			In:   "header",
		}
		params.XSendmuxUploadToken = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "Content-Length",
			In:   "header",
		}
		params.ContentLength = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "upload_id",
			In:   "path",
		}
		params.UploadID = packed[key].(string)
	}
	return params
}

func decodeSendingCompleteAttachmentUploadParams(args [1]string, argsEscaped bool, r *http.Request) (params SendingCompleteAttachmentUploadParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Sendmux-Upload-Token.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Sendmux-Upload-Token",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XSendmuxUploadToken = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Sendmux-Upload-Token",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: Content-Length.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Content-Length",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ContentLength = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
				}).Validate(int64(params.ContentLength)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Content-Length",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: upload_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "upload_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UploadID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^upl_[a-z0-9]{24}$"],
				}).Validate(string(params.UploadID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "upload_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SendingCreateAttachmentUploadParams is parameters of sendingCreateAttachmentUpload operation.
type SendingCreateAttachmentUploadParams struct {
	// Optional client-generated key to make the request idempotent for 24 hours. Replays under the same
	// key return the cached response; a reused key with a different body returns 409
	// idempotency_conflict.
	IdempotencyKey OptString
}

func unpackSendingCreateAttachmentUploadParams(packed middleware.Parameters) (params SendingCreateAttachmentUploadParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IdempotencyKey = v.(OptString)
		}
	}
	return params
}

func decodeSendingCreateAttachmentUploadParams(args [0]string, argsEscaped bool, r *http.Request) (params SendingCreateAttachmentUploadParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIdempotencyKeyVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIdempotencyKeyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IdempotencyKey.SetTo(paramsDotIdempotencyKeyVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.IdempotencyKey.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    0,
							MinLengthSet: false,
							MaxLength:    255,
							MaxLengthSet: true,
							Email:        false,
							Hostname:     false,
							Regex:        nil,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// SendingGetAttachmentParams is parameters of sendingGetAttachment operation.
type SendingGetAttachmentParams struct {
	// Temporary attachment ID returned by an upload endpoint.
	AttachmentID string
}

func unpackSendingGetAttachmentParams(packed middleware.Parameters) (params SendingGetAttachmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "attachment_id",
			In:   "path",
		}
		params.AttachmentID = packed[key].(string)
	}
	return params
}

func decodeSendingGetAttachmentParams(args [1]string, argsEscaped bool, r *http.Request) (params SendingGetAttachmentParams, _ error) {
	// Decode path: attachment_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "attachment_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AttachmentID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        regexMap["^att_[a-z0-9]{24}$"],
				}).Validate(string(params.AttachmentID)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attachment_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SendingGetOpenApiSpecParams is parameters of sendingGetOpenApiSpec operation.
type SendingGetOpenApiSpecParams struct {
	// Weak ETag from a previous response. When it matches the current resource, the server returns 304
	// Not Modified with no body.
	IfNoneMatch OptString
}

func unpackSendingGetOpenApiSpecParams(packed middleware.Parameters) (params SendingGetOpenApiSpecParams) {
	{
		key := middleware.ParameterKey{
			Name: "If-None-Match",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IfNoneMatch = v.(OptString)
		}
	}
	return params
}

func decodeSendingGetOpenApiSpecParams(args [0]string, argsEscaped bool, r *http.Request) (params SendingGetOpenApiSpecParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: If-None-Match.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "If-None-Match",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIfNoneMatchVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIfNoneMatchVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IfNoneMatch.SetTo(paramsDotIfNoneMatchVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "If-None-Match",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// SendingSendEmailParams is parameters of sendingSendEmail operation.
type SendingSendEmailParams struct {
	// Optional client-generated key to make the request idempotent for 24 hours. Replays under the same
	// key return the cached response; a reused key with a different body returns 409
	// idempotency_conflict.
	IdempotencyKey OptString
}

func unpackSendingSendEmailParams(packed middleware.Parameters) (params SendingSendEmailParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IdempotencyKey = v.(OptString)
		}
	}
	return params
}

func decodeSendingSendEmailParams(args [0]string, argsEscaped bool, r *http.Request) (params SendingSendEmailParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIdempotencyKeyVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIdempotencyKeyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IdempotencyKey.SetTo(paramsDotIdempotencyKeyVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.IdempotencyKey.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    0,
							MinLengthSet: false,
							MaxLength:    255,
							MaxLengthSet: true,
							Email:        false,
							Hostname:     false,
							Regex:        nil,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// SendingSendEmailBatchParams is parameters of sendingSendEmailBatch operation.
type SendingSendEmailBatchParams struct {
	// Optional client-generated key to make the request idempotent for 24 hours. Replays under the same
	// key return the cached response; a reused key with a different body returns 409
	// idempotency_conflict.
	IdempotencyKey OptString
}

func unpackSendingSendEmailBatchParams(packed middleware.Parameters) (params SendingSendEmailBatchParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IdempotencyKey = v.(OptString)
		}
	}
	return params
}

func decodeSendingSendEmailBatchParams(args [0]string, argsEscaped bool, r *http.Request) (params SendingSendEmailBatchParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIdempotencyKeyVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIdempotencyKeyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IdempotencyKey.SetTo(paramsDotIdempotencyKeyVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.IdempotencyKey.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    0,
							MinLengthSet: false,
							MaxLength:    255,
							MaxLengthSet: true,
							Email:        false,
							Hostname:     false,
							Regex:        nil,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// SendingUploadAttachmentParams is parameters of sendingUploadAttachment operation.
type SendingUploadAttachmentParams struct {
	// Optional client-generated key to make the request idempotent for 24 hours. Replays under the same
	// key return the cached response; a reused key with a different body returns 409
	// idempotency_conflict.
	IdempotencyKey OptString
	// Exact number of bytes in the binary request body.
	ContentLength int64
	// Filename to associate with the uploaded attachment.
	Filename string
	// MIME type override for the uploaded attachment.
	ContentType OptString
}

func unpackSendingUploadAttachmentParams(packed middleware.Parameters) (params SendingUploadAttachmentParams) {
	{
		key := middleware.ParameterKey{
			Name: "Idempotency-Key",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.IdempotencyKey = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "Content-Length",
			In:   "header",
		}
		params.ContentLength = packed[key].(int64)
	}
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "query",
		}
		params.Filename = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "content_type",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ContentType = v.(OptString)
		}
	}
	return params
}

func decodeSendingUploadAttachmentParams(args [0]string, argsEscaped bool, r *http.Request) (params SendingUploadAttachmentParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: Idempotency-Key.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Idempotency-Key",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIdempotencyKeyVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIdempotencyKeyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IdempotencyKey.SetTo(paramsDotIdempotencyKeyVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.IdempotencyKey.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    0,
							MinLengthSet: false,
							MaxLength:    255,
							MaxLengthSet: true,
							Email:        false,
							Hostname:     false,
							Regex:        nil,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Idempotency-Key",
			In:   "header",
			Err:  err,
		}
	}
	// Decode header: Content-Length.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "Content-Length",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.ContentLength = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
				}).Validate(int64(params.ContentLength)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "Content-Length",
			In:   "header",
			Err:  err,
		}
	}
	// Decode query: filename.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "filename",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    255,
					MaxLengthSet: true,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.Filename)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: content_type.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "content_type",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotContentTypeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotContentTypeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ContentType.SetTo(paramsDotContentTypeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.ContentType.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:    0,
							MinLengthSet: false,
							MaxLength:    255,
							MaxLengthSet: true,
							Email:        false,
							Hostname:     false,
							Regex:        nil,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "content_type",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
