// Code generated by ogen, DO NOT EDIT.

package sending

// OperationName is the ogen operation name
type OperationName = string

const (
	SendingGetOpenApiSpecOperation OperationName = "SendingGetOpenApiSpec"
	SendingSendEmailOperation      OperationName = "SendingSendEmail"
	SendingSendEmailBatchOperation OperationName = "SendingSendEmailBatch"
)
